### ISSUE TITLE
Improve magic behavior between Character Behaviors Enhanced & TK Dodge/Ultimate Combat and The Ultimate Dodge Mod

### ISSUE THREAD

**Issue by cygarniczka** [ShikyoKira/Project-New-Reign---Nemesis-Main#100]
Using three combo of either:
-Character Behaviors Enhanced & TK Dodge & Ultimate Combat 
or
-Character Behaviors Enhanced & Ultimate Combat and The Ultimate Dodge Mod

Will produce faulting dodging behavior when magic is equipped in one or both hands. 
With first mod combination you will not be able dodge at all with magic

With second mod combo you will only be able to do sidesteps that play only half of the animation and not whole sidestep anim.

**Comment by ShikyoKira** [comment]
I use the same setup for my test before. It has nothing to do with Nemesis. If it is related to your load order. I'll leave this open for a week for confirmation

**Comment by cygarniczka** [comment]
> I use the same setup for my test before. It has nothing to do with Nemesis. If it is related to your load order. I'll leave this open for a week for confirmation

What load order did you have for these three combo mods and how did priority look for them in Nemesis?

**Comment by ShikyoKira** [comment]
TUDM's esp must be lower than CBE's esp. File load order doesn't matter.

As of current the priority in Nemesis is not important since conflict isn't significant as I have checked, probably will in the future

**Comment by ShikyoKira** [comment]
More than a week have passed but there is no further update on this matter, so I'll close this issue until we receive more info about it
