### ISSUE TITLE
New animations with multiple motion data lines generate errors

### ISSUE THREAD

**Issue by TudoruData** [ShikyoKira/Project-New-Reign---Nemesis-Main#101]
Trying to create new animations using FNIS's format,

This works:
b -a,Tn,TmctEscapeStop/-0.01 mctEscapeBackwardStart mct_escapeBackward.hkx
MD 0.35 0 0 0

This doesn't
b -a,Tn,TmctEscapeStop/-0.01 mctEscapeBackwardStart mct_escapeBackward.hkx
MD 0.35 0 0 0
MD 0.40 0 -30 0

Error message:
ERROR(1087): Invalid motion data time frame. Previous motion data time frame must be before the current motion time frame
File: FNIS_Engarde_List.txt
Line: 3

**Comment by ShikyoKira** [comment]
Already addressed. Fix will be included in next update. Thanks for reporting
