### ISSUE TITLE
Update Engine runs faster when minimized.

### ISSUE THREAD

**Issue by andrelo1** [ShikyoKira/Project-New-Reign---Nemesis-Main#102]
Update Engine process takes significantly longer time when window is on top, it takes 430 seconds. But if I send window to back or minimize it takes 22 seconds.
Also when window is on top it cause high cpu load and cause other applocations to stuck.

**Comment by ShikyoKira** [comment]
It sometimes takes very long, usually very fast. It seems to be quite random and doesn't seem to have anything to do with minimizing the window. Its a known problem. Still I'll leave this open so that i can come back to it in future

**Comment by andrelo1** [comment]
> It seems to be quite random and doesn't seem to have anything to do with minimizing the window.

May be, but on my side it is 100% reproducible. And it only affect "Update Engine", but not "Launch Engine". I can suppose that it could be related to UI.

**Comment by ShikyoKira** [comment]
wanna clarify this again. Is it that it stuck at 99% for a long time?

**Comment by andrelo1** [comment]
No, it stuck at around 54%.

**Comment by ShikyoKira** [comment]
Ok. Its really hard to pinpoint where it is getting stuck at. Let's discuss this further on discord if you have an account. Drop me a msg there. Shiki - ShikyoKira#3754

**Comment by ShikyoKira** [comment]
I have made changes to the multithreading structure, which i suspect is the cause. Please look into it and see if it has been fixed in the latest version

**Comment by andrelo1** [comment]
I installed 0.82d-beta and issue is not gone. Update process goes much slower when window is on top.

**Comment by ShikyoKira** [comment]
Multithreading structure has been restructured. This problem has been minimized but may still occur to lower end CPU
