### ISSUE TITLE
ZaZ Animation pack [SSE] furniture animations don't work 

### ISSUE THREAD

**Issue by Nepr0** [ShikyoKira/Project-New-Reign---Nemesis-Main#104]
https://www.loverslab.com/topic/100381-zaz-animation-packs-for-se/page/9/?tab=comments#comment-2641521
This seems to be Nemesis issue because I was unable to find any posts with similar problem in the thread. The logs are attached in the post. I used ZAZ 8.0+ UUNP HDT Rev2 : https://mega.nz/#!bEgChJII!kMEg6xU8ERY2F94gn_CEqVfz5ARpCTuiGbe-kp5tD3Y

[Nemesis_Engine.zip](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3264291/Nemesis_Engine.zip)

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3264292/PatchLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3264293/UpdateLog.txt)

[Logs behavior_joints/settings/path/animationdata.zip](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3264295/Logs.txt.zip)
[Nemesis Conflict Tester.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3264297/Nemesis.Conflict.Tester.txt)
Conflict tester lists many animations as duplicates for ZAZ some from Devious Devices Integration and Milk Economy Mod - both which require ZAZ.
[Nemesis LOG.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3264298/Nemesis.LOG.txt)
///
With same mods the ZAZ furniture work on FNIS. I even checked it on the mod setup with no other animation mod but ZAZ's.

IMO the issue must relate to static objects. Pillory from the FunnyBizness animation pack works because it disappears after animations ends. BadEnds - Execution mod hanging scene works too (badends requires ZAZ).

**Comment by ShikyoKira** [comment]
thanks for the report and providing the necessary files. I'll look into it

**Comment by Nepr0** [comment]
We are getting closer to static furniture animation support for characters yes?

**Comment by Nepr0** [comment]
NickaNak posted a fix sweet! Thanks for contacting the author. :D

**Comment by ShikyoKira** [comment]
At the moment, I just need more time to test. The foundation is there already

**Comment by Nepr0** [comment]
> At the moment, I just need more time to test. The foundation is there already

If you need me to test out the static furniture animations I can do that. There is entire testing room with them. If I recall correctly coc zbfTestZone

**Comment by ShikyoKira** [comment]
Do you have discord? its easier to discuss it there and there might be other stuffs i would like to ask you to test due to privacy reason

**Comment by Nepr0** [comment]
Yeah I can do that point me to the link.

**Comment by ShikyoKira** [comment]
drop me your discord username, i'll pm u the link

**Comment by Nepr0** [comment]
Same username like here.

**Comment by ShikyoKira** [comment]
need full username including the code after it

**Comment by Nepr0** [comment]
Nepr0#4896

**Comment by ShikyoKira** [comment]
fixed in v0.83
