### ISSUE TITLE
Download is stuck at the end

### ISSUE THREAD

**Issue by nahsche** [ShikyoKira/Project-New-Reign---Nemesis-Main#105]
Hi. Like title say. 
I'm using chrome

Edit: solved. I use uGet to download the file

**Comment by ShikyoKira** [comment]
lol ok. Download has nothing to do with this program for sure. It is likely a problem with the connection to this domain

**Comment by nahsche** [comment]
Thanks :)). Im already can download Nemesis. Sounds very promising. Great
job sir. Im a fan of your ultimate dodge. Im trying to make TUDM sidestep
only for NPC and player by default (I dont like MCM). Change dodgestyle in
.esp does nothing. Im very noob thoug

Thanks for reply. Good luck
