### ISSUE TITLE
Behavior engine detecting mods that I don't have installed

### ISSUE THREAD

**Issue by CrimsonKL** [ShikyoKira/Project-New-Reign---Nemesis-Main#108]
This is the error message

Checking engine version
Engine is up to date

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: tudm
Mod Checked 3: tkuc

Mod installed: bbdarksoulscombat
Mod installed: Engarde
Mod installed: FlowerGirls
Mod installed: HalosPoser2
ERROR(4011): Alternate animation file has not been registered. Please contact the mod author
File: FNIS_NAR_List.txt
Line: 59
Animation File: NAR0_DW1HM1HMBlockBash.hkx

Failed to generate behavior

I dont have installed bbdarksoulscombat, Engarde, FlowerGirls or HalosPoser2
What sould I do?

**Comment by CrimsonKL** [comment]
I forgot to mention that I dont have animated aromory either

**Comment by ShikyoKira** [comment]
run MO2 visual explorer. Go to `data/meshes/actors/character/animations` look into the folders located in that directory, check if there is any txt file starting with `FNIS_`

**Comment by CrimsonKL** [comment]
There is

**Comment by ShikyoKira** [comment]
Look for those files `FNIS_bbdarksoulscombat_List.txt`, `FNIS_FlowerGirls_List.txt` and so on. If they are there, find where its source. Make sure they aren't located in your data directory
