### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by lans139** [ShikyoKira/Project-New-Reign---Nemesis-Main#109]
hi ShikyoKira i heart about you Project New Reign Nemesis from 2 days almost and i say i will give a shot to try it i use MO1 86x and i use skyrim legendary game i download u Nemesis.Unlimited.Behavior.Engine.v0.82d-beta file and try it i delete all fnis file and try to update engine its give me error 2022
![Untitled](https://user-images.githubusercontent.com/54302262/63319209-98ffa400-c319-11e9-9650-48ce770d7c50.jpg)
i know how to use any program on MO1 i mean how to active it correctly 
![2d](https://user-images.githubusercontent.com/54302262/63319289-da904f00-c319-11e9-8be0-b7d1a60dd022.jpg)
hope u can tell me what do to cuz i search more than 4 hours for any advice and found nothing.
and sorry for my bad English its suck i know ^^".

**Comment by ShikyoKira** [comment]
post your `updatelog.txt` located in `data/nemesis_engine`. Which locale are you in? I noticed the some characters aren't working right

**Comment by lans139** [comment]
here my updatelog.txt

[2019-Aug-21 01:42:50] Nemesis Behavior Version: v0.82d
[2019-Aug-21 01:42:50] Current Directory: D:\Anubis\PC games\offline games\Skyrim\The Elder Scrolls V Skyrim - Legendary Edition\data\Nemesis_Engine
[2019-Aug-21 01:42:50] Data Directory: D:\Anubis\PC games\offline games\Skyrim\The Elder Scrolls V Skyrim - Legendary Edition\Data\
[2019-Aug-21 01:42:50] Skyrim Special Edition: FALSE
[2019-Aug-21 01:42:50] Detecting processes...
[2019-Aug-21 01:42:55] Process count: 117
[2019-Aug-21 01:42:55] Global reset all: TRUE
[2019-Aug-21 01:42:55] Initializing file check...
[2019-Aug-21 01:42:55] File Check complete
[2019-Aug-21 01:42:55] External script run complete
[2019-Aug-21 01:42:55] Temp behavior clearance complete

**Comment by lans139** [comment]
OK when i install it to data folder directory its work :\ but from  MO1 folder directory doesn't work

**Comment by ShikyoKira** [comment]
its ok. i can understand it just fine. oh good. yea install it directly sometimes work. As for sexlab, i still need extensive testing to find out. Do you mind test other animation mods as well to be sure others are working or not?

**Comment by lans139** [comment]
look i test this now if u install any animation mod from NMM and active it with Nemesis will work but MO1 no maybe because NMM install any mod from directory data folder iam not totally sure but that all i can figure out the problem here man MO1 is better choice from NMM :\

**Comment by ShikyoKira** [comment]
Me and my several testers have tested it. It is working fine. So this is likely on your end. Try it in a clean load order as well as a new game. Make sure you have updated your mods as well as using the latest version of Nemesis. If still doesn't work, you can try older version of Nemesis

Those files you have pointed out are being patched by Nemesis. So you must make sure they are located at the lowest in your left panel MO/MO2. Update me after you have done further testing

**Comment by lans139** [comment]
hello ShikyoKira i did everything us u say same problem osex and sexlab animation just freeze
and take a look in that
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3538630/PatchLog.txt)
a lot of error and warning don't know i just give up i think i will back to fnis :(

**Comment by ShikyoKira** [comment]
yes, if it isn't working. Come back next time. As i have no idea how to recreate this issue, even with my testers

**Comment by ShikyoKira** [comment]
Kindly try v0.83. If problem persist, this issue will remain open. An update will be appreciated. Thank you very much

**Comment by ShikyoKira** [comment]
No update for more than a month. I'll close this issue assuming it has been fixed in the latest version
