### ISSUE TITLE
Trying to convert my install of Enderal to SSE, getting animation errors in Nemesis

### ISSUE THREAD

**Issue by Spudnik1** [ShikyoKira/Project-New-Reign---Nemesis-Main#110]
Hi,
I am trying to convert my install of Enderal to SSE.
I successfully converted all the files and meshes of all the Enderal files with CAO.
When I launch Nemesis and Launch the Nemesis Engine, I get a lot of warnings about the "Animation has not been registered in defaultmale.hkx file. The animation will not work. Please contact the mod author"
Here is the full log of the warnings:
[nemesis-log-error.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3556778/nemesis-log-error.txt)

I hope that we can find a solution to this.

**Comment by ShikyoKira** [comment]
Are you by any chance the author of Enderal?

**Comment by Spudnik1** [comment]
No, I'm not that good :D. I'm just someone who is trying to do a DIY conversion of the mod.

**Comment by ShikyoKira** [comment]
Can you quote the last line of the log for me?

**Comment by Spudnik1** [comment]
Ya sure, here:
[https://pastebin.com/915Mw3fp](https://pastebin.com/915Mw3fp)

**Comment by ShikyoKira** [comment]
can you type out the message here?

**Comment by Spudnik1** [comment]
IGNORE THE WARNING MESSAGE(S) IF YOU ARE NOT THE MOD AUTHOR. IT IS FOR DEBUGGING PURPOSES

**Comment by ShikyoKira** [comment]
There you go. Ignore it

There is nothing i can do about it. Its not my problem. Nemesis only reports it. Only the mod author knows what to do about it. I have intentionally hide these messages behind a button, even added a big all caps message at the bottom. Kindly please the message and only report if there is an actual issue like what isn't working

**Comment by Spudnik1** [comment]
ok, sorry for opening this issue, I'll just ignore the message and carry on.

**Comment by ShikyoKira** [comment]
1 more thing. Sometimes, the mod author can be aware of the warning but choose to ignore it because it is something they intentionally do to achieve certain result that they want
