### ISSUE TITLE
Error 5011

### ISSUE THREAD

**Issue by madmot** [ShikyoKira/Project-New-Reign---Nemesis-Main#111]
Checking engine version
Engine is up to date

Initializing behavior generation

Running script: pythontutorial.py
Running script: script1.bat

Mod Checked 1: nemesis
Mod Checked 2: agpo
Mod Checked 3: tudm
Mod Checked 4: tkuc

Mod installed: BBDarkSoulsCombat
Mod installed: FNISBase
Mod installed: FNIS_PCEA2
Mod installed: PotionAnimatedFix
ERROR(5011): Original header for "animationsetdatasinglefile.txt" is not found. Please contact the template creator
Template: b
Project: DefaultFemale.txt
Header: __folder_managed_by_vortex

Failed to generate behavior

**Comment by ShikyoKira** [comment]
install Nemesis manually if you are using vortex

**Comment by madmot** [comment]
I didnt install it with vortex

**Comment by chriku** [comment]
same issue. @madmot what was your solution?
