### ISSUE TITLE
TUDM patch bugs out animations.

### ISSUE THREAD

**Issue by zodiac213** [ShikyoKira/Project-New-Reign---Nemesis-Main#114]
When patching TUDM with Nemesis,all animations bug out and cause actors and players to be stuck in idle animations.

**Comment by ShikyoKira** [comment]
more context pls

**Comment by zodiac213** [comment]
It seems to have been a conflict of some sort. I'm using MO2 and used Nemesis to patch all my animations,but using the TUDM patch on my main profile with all my mods would seemingly break all animations in my game. But than I created a new account with only Nemesis and animation mods activated and then patched again,this time with all animations working flawlessly. 

For the curious,also using AGO,Immersive Animations,Engarde,Character Behaviours,TUDM and Ultimate Combat.

**Comment by ShikyoKira** [comment]
hmm.. well as you said, it seems like a conflict issue, so I'll just close this issue. You can continue post more info regarding what mod is TUDM conflict with.

Thanks for reporting
