### ISSUE TITLE
Mod errors

### ISSUE THREAD

**Issue by VilainPetitCanard** [ShikyoKira/Project-New-Reign---Nemesis-Main#117]
Dear shikyokira

Very nice tool, almost all mods work without any problems and as expected.
I only found two mods that didn't work:
-Art of the catch crashes the compiler in all versions
-Immersive Animated Looting doesn't work in the newest version (0.82d), but does in older ones (0.80a). When compiling with the newest version, it CTD's the game on activating anything.

Could you look into those errors?

**Comment by ShikyoKira** [comment]
The immersive animated looting crash has been fixed. It is due to the interaction between PCEA.

I will look into the art of the catch crashes. May I know what kind of crashes you get? Whats the message? Does it crash even in a clean load order?

**Comment by VilainPetitCanard** [comment]
Alright, looking forwart for the next release then ;)
With Art of the Catch, I always get this error: [2019-Oct-28 16:13:53] WARNING(1026): Invalid option | File: FNIS_ArtOfTheCatch_List.txt | Line: 3 | Option: Tn

**Comment by ShikyoKira** [comment]
Can you just... ignore all warnings messages. I cannot stress how many times I have to say this that warning messages are meant for mod authors not mod users, I have hidden it behind a button for a reason and at the end of the log I have stated very very clear to ignore all warning messages. And please, patchlog/updatelog is not for users also. 

Kindly... i really mean it. Kindly don't freak out because of messages even thought nothing is broken. Please only come back to me when something is broken

**Comment by VilainPetitCanard** [comment]
I'm sorry, I didn't mean no offense. And the immersive animated looting bug is a serious one nonetheless, and I haven't seen it reported anywhere, so I thought I'd report it here...
In fact, the patcher failed/crashed the first few times when I activated Art of the catch, with this warning message showing, so I thought it would be because of it and ran the patcher without art of the catch enabled - and it completed successfully. But yesterday I retried with art of the catch enabled, and it completed only showing the warning - so probably it was something else that crashed the patcher.

**Comment by ShikyoKira** [comment]
Hmm.. the patcher crash might be the cpu core issue. This tool is quite cpu intensive. I'll see if i can structure the cpu load much more effective. Whats your pc spec?

**Comment by VilainPetitCanard** [comment]
6700k, 32gb ram...should surely be powerful enough.

**Comment by ShikyoKira** [comment]
hmm perhaps you have background process running at that time like how it crashed for me occasionally as well. I'll see if I can make the thread more stable

**Comment by ShikyoKira** [comment]
should be fixed in v0.83. I'll close this for now assuming it has been fixed. Will reopen this if problem persist
