### ISSUE TITLE
First person not working

### ISSUE THREAD

**Issue by Velgus** [ShikyoKira/Project-New-Reign---Nemesis-Main#123]
EDIT: Original post no longer relevant.

**Comment by ShikyoKira** [comment]
It would be helpful if you can provide the PatchLog.txt as well. Generally PatchLog.txt is the one affecting the game.

**Comment by Velgus** [comment]
I don't know what exactly changed that fixed it, but it doesn't crash anymore. 

That said, I've noticed a few problems in-game, such as first-person dodging with TK Dodge not functioning. The animation with the weapons moving works, but the character doesn't actually move with the dodge (except for the forward dodge).

3rd-person animations all seem to work fine.

The TK Dodge/Ultimate Combat option was checked during patching.

**Comment by ShikyoKira** [comment]
Perhaps mod conflict? Oh well, so long it works xD

Yea, another tester told me about first person not working. I'm working on it. Thanks for informing. I'm changing this issue to first person not working from now on
