### ISSUE TITLE
ESL flagged FNIS.esp would be nice for SSE

### ISSUE THREAD

**Issue by Ne0niq** [ShikyoKira/Project-New-Reign---Nemesis-Main#128]
Hi, Shikyo! 
Well, as the title says: I think there is not point to give a regular plugin slot for FNIS dummy.

Not a problem at all, but I will be very grateful for generating FNIS.esp with ESL flag out of the box. Currently I have to do it when I am updating everything and rebuilding the patch from scratch.

Thanks in advance!

**Comment by ShikyoKira** [comment]
sure

**Comment by Ne0niq** [comment]
heh, it seems, that setting a ESL flag is a bad idea, because I just discovered that FNIS Sexy Move will stop working if FNIS.esp has a ESL flag. Ridiculous situation, but this is how Fore's mod works. I don't understand why, because there are no FormID's inside the dummy file, so no shifted address can be.

I have not much necessary request, but still: Shikyo, can you please give me an invite on your Discord server, if you have one? I would report you some things in more convenient way, if I discover bugs or have a suggestion. 
My ID: 
NeOniq#3811

**Comment by ShikyoKira** [comment]
hmm if thats the case i'll just close this then
