### ISSUE TITLE
Error (3007) please help.

### ISSUE THREAD

**Issue by Cristankick** [ShikyoKira/Project-New-Reign---Nemesis-Main#129]
I've reinstalled it twice already. please help.
CRITICAL ERROR: Wrong error input. Please re-install Nemesis

CRITICAL ERROR: Wrong error input. Please re-install Nemesis

ERROR(3007): Invalid function call. Function call cannot be use in this line for it is not in line with the format. Please contact the template creator
Template: tkuc
File: mod\tkuc\animationdatasinglefile\FirstPerson~1\346.txt
Line: 14

**Comment by ShikyoKira** [comment]
kindly post your updatelog.txt and patchlog.txt if you have it

**Comment by ShikyoKira** [comment]
no update on this issue for more than a month. Closed
