### ISSUE TITLE
Minor Feature Request - Completion Message

### ISSUE THREAD

**Issue by Dakraid** [ShikyoKira/Project-New-Reign---Nemesis-Main#130]
So this is a really minor request: a small log message saying "Nemesis generation complete - You can now close the utility." or something similar.

This would clearly indicate that the process is finished, as of now the tool gives a progression bar but with the flashing bar telling you about how many animations you have it doesn't feel clear enough. A small message informing the user that the tool is save to close would be appreciated. Thank you.

**Comment by ShikyoKira** [comment]
Isn't it there already? I believe you should see this message "Behavior generation complete" when it is complete. No?

**Comment by Dakraid** [comment]
I'm sorry, I did go back and check again and it seems to be there. I'm not sure if I just missed it the first few times around, or if there was something causing an issue? Could maybe an error in one of the Python script cause it to not display?

**Comment by ShikyoKira** [comment]
Nvm. If it ever happen, create a new issue and post your patchlog.txt right away. Don't try to patch it again before you save that log. I will close this issue now. Thanks
