### ISSUE TITLE
Devious Devices SE Armbinder and Yoke animation are swapped

### ISSUE THREAD

**Issue by Ryte424** [ShikyoKira/Project-New-Reign---Nemesis-Main#134]
I noticed the Armbinder Animation in Devious Device is swapped with Yoke Animation while standing and vice versa. Sneaking/crouching show the correct animation

**Comment by ShikyoKira** [comment]
Thanks for reporting. Will look into it

**Comment by Light2020** [comment]
I've also had an issue with DD's idles being swapped around with nemesis. Though it's not only DD, it's a couple mods that handle idle animations, like the LoS Cover animation and Combat Fatigue. They all get swapped around with each other. 

So I think it's just an issue with idles in general.

**Comment by ShikyoKira** [comment]
ah nice. This gives me more clue into it. So I guess its just like you said, an issue with idles in general Thanks

**Comment by ShikyoKira** [comment]
finally got the chance to did some testing. Yes, it is indeed as you said. I'll start fixing it asap
