### ISSUE TITLE
CTD when using Halo Poser with other mods

### ISSUE THREAD

**Issue by ShikyoKira** [ShikyoKira/Project-New-Reign---Nemesis-Main#135]
Having Halo Poser itself does not crash. However, upon using other animation mods, it will crash

**Comment by Keitsoru** [comment]
I think what it is that the number of poses with Halo's is just SO high that the current version of the engine can't handle it. I can run it alongside smaller mods. Sexlab itself is fine, Animated Armory is fine. But the amount is jsut so large that anything too big pushes it over that threshold with Halo's.

**Comment by ShikyoKira** [comment]
Duplicate of #178
