### ISSUE TITLE
ERROR(6002): An exception has occured while patching.

### ISSUE THREAD

**Issue by Simonuell** [ShikyoKira/Project-New-Reign---Nemesis-Main#136]
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: Alternate Animation
Message: boost::filesystem::copy_file: �������� � �������: "Papyrus Compiler\backup scripts\Actor.psc", "Papyrus Compiler\scripts\Actor.psc"

Failed to generate behavior
Hello! I am writing to you, because I have stuck with this problem. Everytime I try to generate my animations, this shows up. Is there anything has to be deleted? Does your mod use its own Papyrus compiler? Thanks in advance!

**Comment by Simonuell** [comment]
The problem occurs also when I am trying to install XP32MSE

**Comment by Simonuell** [comment]
Is there a version of XP32 for nemesis especially??

**Comment by ShikyoKira** [comment]
Nope. Nemesis supports XP32. Try restarting your PC and give it a few tries. Make sure you are using the latest version

I'll remove papyrus dependency in next version count v0.84 onwards eliminating Papyrus related issue in the future

**Comment by ShikyoKira** [comment]
Fixed in v0.84
Duplicate of #195
