### ISSUE TITLE
Spear animations are not done by Nemesis

### ISSUE THREAD

**Issue by ItsADogPen** [ShikyoKira/Project-New-Reign---Nemesis-Main#137]
Hi there,

I am currently using mods including SkyrimSouls and True Spear Combat with spear weapons from various mods like Immersive Weapons and etc. I've ran Nemesis tool and it looks like it doesn't do the spear animations for these spears but instead gets overwritten by other non-spear two-handed animations. I was wondering if it's an addressed issue already and if so, how do I fix?

(Also sent a PM by Reddit just in case github is down)

**Comment by ItsADogPen** [comment]
Hi there,

Just to let you know, I did some more testing after isolating a conflicting patch .esp and tried running with SkyrimSouls as well. It appears that the spear animations made it in on most spears except some. I guess it might be to do with a lack of support on those spear mods or maybe the spears themselves. Might be something you might want to debug with the other mod creators.

Anyway, spears are a must in my playthrough so if you need someone to test spear mods for your Nemesis tool for any conflicts/missing animations just let me know.

**Comment by ShikyoKira** [comment]
Noted. I'll give it a look after my holiday. Thanks for reporting

**Comment by ShikyoKira** [comment]
have you tried using Animated Armoury's spear?

**Comment by ShikyoKira** [comment]
No update on this issue for more than a month. Closed
