### ISSUE TITLE
Issues with Critical Hit - Backstabs and Parries

### ISSUE THREAD

**Issue by micmou** [ShikyoKira/Project-New-Reign---Nemesis-Main#139]
I do not personally use it but there is a problem with the mod listed here
https://www.nexusmods.com/skyrimspecialedition/mods/17400?tab=description

it seems the animations bug out and dont play. Multiple users say that Nemesis gives a error but does not post the error...

If you need help testing this and discovering the root let me know.

**Comment by ShikyoKira** [comment]
They aren't using the latest version. It has been fixed. Thanks for pointing out tho
