### ISSUE TITLE
Issues with undressing animations

### ISSUE THREAD

**Issue by Keitsoru** [ShikyoKira/Project-New-Reign---Nemesis-Main#145]
Hey, so, I use a mod to undress the PC for things like bathing, etc. The initial animation plays fine, but then my character jumps, floats as if the game can't find solid land to put her on, then lands and is stuck crouching. Once this happens, I can't get her to stand back up, Can't attack or anything. Any idea how to fix?

**Comment by Keitsoru** [comment]
Update, and two things to note:

1. It was all Sexlab animations. Not just the undress animation.

2. I also had CBE installed. I made sure it was checked and everything in Nemesis, but, for some reason, it just doesn't play nice with Sexlab animations.

**Comment by ShikyoKira** [comment]
Does it mean that without CBE installed, everything is fine?

**Comment by Keitsoru** [comment]
Correct. Everything seems to be fine without CBE installed. Whether it's something needing resolved on CBE's side, or something you can address with Nemesis, I have no idea.

**Comment by ShikyoKira** [comment]
well, its CBE side. CBE is known to be buggy anyway. It breaks the killmove animation too. Too bad Zartar (the author) no longer update it. Its a dead mod anyway. So treat it like an experimental mod, not something you should add in your playthrough

I'll close this issue from now on. Thanks for the update
