### ISSUE TITLE
t-posing in oldrim

### ISSUE THREAD

**Issue by josephV013** [ShikyoKira/Project-New-Reign---Nemesis-Main#147]
hi ...i recently installed nemesis in my oldrim.. after i update it and launch nemesis behavior engine it causes all humanoids to tpose..

[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4176783/UpdateLog.txt)

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4176784/PatchLog.txt)

it says. Animation has not been registered in defaultmale.hkx file. ..it happened to all hkx files... what should i do... what did i do wrong.... do i need to install fnis??

**Comment by ShikyoKira** [comment]
you don't seem to be using the latest version. Apart from that, i noticed you aren't using a legitimate skyrim. Nvm that, Nemesis should be able to support that still. If updating it to the latest version still doesn't work, manually install it in your data folder like a normal mod

**Comment by josephV013** [comment]
im using nemesis ver0.83c... im pretty sure thats the latest version...i install it using MO2... i tried installing it manually in my data folder ...same result..T-pose.

**Comment by josephV013** [comment]
i think it has something to do with the default/fe/male.hkx and firstperson.hkx ... anmations is not registering.....i wonder why...

**Comment by ShikyoKira** [comment]
are you using the MO2's `start in` function to run Nemesis?

**Comment by josephV013** [comment]
yes..

**Comment by josephV013** [comment]
any informationg about this line??  "Animation has not been registered in defaultmale.hkx"...

**Comment by josephV013** [comment]
I fixed it!!!!... i just reinstalled skyrim and nemesis... and suddenly it works.... thanks for the help good sir...

**Comment by ShikyoKira** [comment]
O.o ah well, glad you fixed it lol. I'll close this issue then. Thanks for the update =)
