### ISSUE TITLE
Stuck at 100%

### ISSUE THREAD

**Issue by denizay24** [ShikyoKira/Project-New-Reign---Nemesis-Main#148]
Hello there. Nemesis stucks at 100% after I press "Launch Nemesis Behavior Engine". I've waited around 1 hour at 100% but nothing happens. PatchLog.txt stops updating as well. I'm on latest Nemesis version(0.83c SE).

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4181342/PatchLog.txt)
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4181343/CriticalLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4181344/UpdateLog.txt)

**Comment by denizay24** [comment]
I've solved the problem by changing the Windows language to English.

**Comment by ShikyoKira** [comment]
hmm thats weird. I'll take your fix as a temporary fix if i receive other report about it. Thanks

**Comment by nishio17** [comment]
Hi there,
I'm using 0.83c(LE) and I have the same problem.
I tried changing the language of Windows, reinstalling the mod, restarting the PC and it didn't improve.
0.82d didn't have this problem.
However, Animated Armory  don't work when using 0.82d.
Using only minimal mods didn't work.
Other mods (e.g. TUDM) are working at 0.82d.
Do you know the cause?

[PatchLog_0.82d.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4198319/PatchLog_0.82d.txt)
[UpdateLog_0.82d.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4198323/UpdateLog_0.82d.txt)
[animationdatasinglefile_0.82d.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4198325/animationdatasinglefile_0.82d.txt)

[PatchLog_0.83c.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4198328/PatchLog_0.83c.txt)
[UpdateLog_0.83c.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4198329/UpdateLog_0.83c.txt)
[animationdatasinglefile_0.83c.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4198330/animationdatasinglefile_0.83c.txt)

**Comment by denizay24** [comment]
Forgot to mention that I also moved Skyrim out of Program Files, maybe that could help as well.

**Comment by nishio17** [comment]
Thanks for the hint.
This cause was tools such as TES5Edit, xTranslator, and Papyrus Compiler were placed in the Skyrim installation folder.
Moving all of these tools to another location, Nemesis worked without problems.

**Comment by ShikyoKira** [comment]
Thanks for the report. it seems to be checking unnecessary files, I'll double check and see if there is anything i can do about it. While "changing the Windows language to English" is indeed weird. Nevermind, so long it is working fine for you guys.

**Comment by oguba** [comment]
I changed the language and moved SSEEdit and Papyrus Compiler to a different location, but I'm still stucked. I tried earlier versions and almost all of them gave me error 1185 and the ones that didn't give the got stuck at 100% too. Here are my files:

[url=https://drive.google.com/file/d/1i_awVO0jkxcEcFKg-32sGh9PSSukuszd/view]PatchLog.txt[/url]
[url=https://drive.google.com/file/d/1vTqJZHsCej1NICPArf8xcXIkIo-ihoR1/view]CriticalLog.txt[/url]
[url=https://drive.google.com/file/d/1oGRGjV_4stUzdg0tmGJ5Atk3OJeOB0aP/view]UpdateLog.txt[/url]

**Comment by oguba** [comment]
I changed the language and moved SSEEdit and Papyrus Compiler to a different location, but I'm still stucked. I tried earlier versions and almost all of them gave me error 1185 and the ones that didn't give the got stuck at 100% too. Here are my files:

PatchLog.txt - https://drive.google.com/file/d/1i_awVO0jkxcEcFKg-32sGh9PSSukuszd/view
CriticalLog.txt - https://drive.google.com/file/d/1vTqJZHsCej1NICPArf8xcXIkIo-ihoR1/view
UpdateLog.txt - https://drive.google.com/file/d/1oGRGjV_4stUzdg0tmGJ5Atk3OJeOB0aP/view

**Comment by oguba** [comment]
I changed the language and moved SSEEdit and Papyrus Compiler to a different location, but I'm still stuck. I tried earlier versions and almost all of them gave me error 1185 and the ones that didn't give the error got stuck at 100% too. Here are my .txt files:

PatchLog.txt - https://drive.google.com/file/d/1i_awVO0jkxcEcFKg-32sGh9PSSukuszd/view
CriticalLog.txt - https://drive.google.com/file/d/1vTqJZHsCej1NICPArf8xcXIkIo-ihoR1/view
UpdateLog.txt - https://drive.google.com/file/d/1oGRGjV_4stUzdg0tmGJ5Atk3OJeOB0aP/view

**Comment by pw508** [comment]
I seem to be having the same problem. My windows language is English already and I tried removing Tes5edit and Papyrus Compiler out of my installation folder with no success. It freezes at 100% after a few seconds of processing. 

If you're still checking to see if there's anything you can do about it then no problem, I just thought I'd add my report. Lots of really cool Nemesis mods are coming out and it'd be awesome to get on board

**Comment by Taranis312** [comment]
Hi, I'm also having the same problem. My windows won't let me change my language (windows 10 home 64 bit single language) 
Moving TES5Edit, xTranslator and papyrus compiler didn't work either.

**Comment by oguba** [comment]
Problem in my end was XPMSE. After disabling it, Nemesis would finish patching without a problem. Then I messed around with XPMSE's installer and in character creation part in the installer, I choosed none instead of racemenu or MCM. With that Nemesis didn't get stuck at %100 even with XPMSE enabled.

**Comment by Taranis312** [comment]
Right it seems to be working now. Thank you! Let me check in the game to see if anything is missing

**Comment by pw508** [comment]
I fixed this last night and came to report on how I fixed it, I'm glad others had success too. 

My problem was XPMSE as well but all I did was remove the XPMSE folder from my animations folder while running Nemesis and then put it back in after. I don't know what effects this could have but after testing it out last night and a bit this morning everything seems to be working properly.

**Comment by Taranis312** [comment]
Welp, everything worked fine but it seems Animated Armoury is also causing the same problem

Checking engine version
Engine is up to date
Version Code: 2176-7277

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: agpo
Mod Checked 3: dscgo
Mod Checked 4: tkuc

Mod installed: FayeFG
Mod installed: FlowerGirlsSE
Mod installed: NAR

**Comment by Taranis312** [comment]
I forgot to upload my logs so here they are 
Both Animated Armoury and XPMSE (with character creation enabled) stucks at the same step
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4460431/UpdateLog.txt)
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4460432/PatchLog.txt)

**Comment by gislira** [comment]
My nemesis was stuck at 99% also,  Then i fixed it by getting microsoft net framework EXCATLY version 3.5
