### ISSUE TITLE
CTD Unless Meshes And Scripts Folder Is Deleted

### ISSUE THREAD

**Issue by Cheaparse** [ShikyoKira/Project-New-Reign---Nemesis-Main#151]
This happens on both modded and unmodded versions. I use MO2, and not exactly sure why it is happening. Nemesis worked before, and I did a clean save+cleared out any remnants of FNIS.

**EDIT:** Isolated the problem to whatever files Nemesis creates in the overwrite folder of MO2. Was able to start the game when: deleting the entire folder (including the created FNIS.esp file) or deleting the scripts and meshes folder.

Am not able to start the game in any way when the FNIS.esp is enabled in any way. This includes when I turn the overwrite folder into a mod, whether it is activated or not.

**Comment by ShikyoKira** [comment]
wait.. how can unmodded version not work? how many animations do you have installed? The counter displayed by Nemesis

Send me your patchlog.txt

**Comment by Cheaparse** [comment]
Sorry, should clarify - Launching through mod organizer SKSE (normal way) launching with Skyrim (without SKSE? Unmodded

**Animations** - 1,4214
**Warning Count** - 8094

The file is just repeating this over and over along with several other errors. I'm just going to call it a draw and wait a bit before jumping in feet first again. Spent the entire day troubleshooting a windows update on a few computers, so kind of tapped out. Thanks for the reply, will be following the mod closely.

> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\sneakwalk_right.hkx
> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\special_basketchickenfeed.hkx
> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\special_ceremony1welcome.hkx
> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\special_ceremony2blessing.hkx
> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\special_ceremony3chest.hkx
> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\special_ciceroagitated.hkx
> [2020-Feb-13 03:33:36] WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author | Animation: animations\special_cicerodance1.hkx
