### ISSUE TITLE
Possible fix to a bug

### ISSUE THREAD

**Issue by Tskcool** [ShikyoKira/Project-New-Reign---Nemesis-Main#153]
I was having an issue where Nemesis kept giving me a 6002 error whenever I launched it from MO2 but worked perfectly when I launched it separately. 

Turns out I had leftover files from FNIS PCEA2 when I disabled it in MO2 and Nemesis kept thinking it was installed even though it wasn't, giving me that error. 

Removing those leftover files fixed it for me. Might be worth looking into why that's happening.

**Comment by ShikyoKira** [comment]
Not a bug. As stated it can't be used together with FNIS PCEA2 in the PCEA page. It will be considered faq and be included in it in the future. Thanks
