### ISSUE TITLE
eating sleeping driinking cant Compatible?

### ISSUE THREAD

**Issue by kangbs1215** [ShikyoKira/Project-New-Reign---Nemesis-Main#158]
thanks to nice work
i use to google translate sry

https://www.nexusmods.com/skyrim/mods/52269?tab=description

use to nemesis engine,  eating, open the door etc... animation end -> jumping animation bug & cant control my charactor

oh sry Character Behaviors Enhanced coflict

**Comment by ShikyoKira** [comment]
if it is conflict with Character Behavior Enhanced, then it is not Nemesis' fault. It is Character Behavior Enhanced or the mod's fault. I would say its CBE's fault because many people say it is buggy

Kindly confirm to me that if removing CBE fixes or problem

**Comment by kangbs1215** [comment]
not nemesis problem. i remove to cbe. -> not buggy jump animation.
