### ISSUE TITLE
FNIS Sexy Moves did not detect FNIS.esp

### ISSUE THREAD

**Issue by DroidZed** [ShikyoKira/Project-New-Reign---Nemesis-Main#159]
Hi, I'm having this issue :
When I run the game a show box appears and tells me that FNIS.esp is not active despite being active in my load order :/ 
I'm going to remove it for now, but I hope you'd look into it and try to fix this please.
Thanks !

**Comment by ShikyoKira** [comment]
Did you esl the FNIS.esp?

**Comment by DroidZed** [comment]
Nope I did not.

**Comment by ShikyoKira** [comment]
how about you copy the FNIS.esp from FNIS and remove its content?

**Comment by DroidZed** [comment]
Sorry for the late reply, but how do I remove the content of an EPS ? I don't have much knowledge in modding so I would be glad that you'd explain it to me :) and thanks.

**Comment by NielsGx** [comment]
I use Nemesis engine and it's working great. But when I try to install fnis sexy move, it won't create the fnis.esp dummy file. Any fix? Using MO2, and 360behavior movement patch

**Comment by IdaeroAce** [comment]
I use FNIS sexy move and it works o.o

**Comment by DroidZed** [comment]
I did not install FNIS,maybe the esp from FNIS has some sort of code that makes it recognizable by Sexy Move ?

**Comment by DroidZed** [comment]
And also I can't delete the FNIS esp because XPMSE32 needs it (Along with other FNIS-needing mods)

**Comment by tnsolley** [comment]
I've just reactivated/revived my "old" modlist to work with game v'.1170, I'm finding that I get the aforementioned error in-game upon enabling a few OSA mods -- which I find odd, because both FNIS and Pandora seem to have no issues handling the animations? FNIS returns with no consistency issues, and Pandora returns no errors (side note let me know if there's a problem running FNIS and Pandora sequentially)...

**Comment by DroidZed** [comment]
@tnsolley I don't think you should be using them both. Nemesis came to replace FNIS then later Pandora to replace Nemesis. Only use one behavior engine and it's much better to stick with the one giving you better resulsts.
