### ISSUE TITLE
incompatible with real flying

### ISSUE THREAD

**Issue by JhonAkira** [ShikyoKira/Project-New-Reign---Nemesis-Main#162]
I reinstalled all of my mods and generated all the animation using nemesis however, when i tried to use real flying, it doesn't let me glide. The wings pop out however, gliding doesn't work. When i tried to use flight, i was able to fly however, my character remains stuck in the flying animation once I land.

**Comment by ShikyoKira** [comment]
thanks. I'll give it a try. SE or LE to be exact?

**Comment by JhonAkira** [comment]
Hi there. I'm currently using LE version of real flying.

**Comment by ShikyoKira** [comment]
im wondering. Are you using CGO?

**Comment by JhonAkira** [comment]
Hi. Yes. I was using CGO and a couple of behavior files as well but i uninstalled them to test the real flying animation to see if they're causing the issue.

**Comment by ShikyoKira** [comment]
Well, i have tested it. And apparently real flying can become buggy when use along some behavior mods. CGO is 1 of the mods i have confirmed that cause issue with it. I tested real flying with a clean load order as well as a load order with full of animations but without CGO and any other behavior modifying mods. It is working as expected

Update me once you have confirmed that

**Comment by JhonAkira** [comment]
Hi, i tested the animations again and it looks like the mod 360 behavior is the one causing the issue. Its strange though since I did uninstall it together with my other animation and behavior mods when i tested real flying before. Maybe I didn't uninstall it correctly back then. Anyway, all is working now and thanks for looking into this.
