### ISSUE TITLE
Jumping animation is playing, but characters are floating

### ISSUE THREAD

**Issue by ShikiRyugi** [ShikyoKira/Project-New-Reign---Nemesis-Main#168]
I have another (though minor) issue,
the NPC sometimes jump and then are 'stuck' floating and moving while floating instead of just walking for 1-2 sec onwards.

**Comment by ShikyoKira** [comment]
remove all mods and test again. Kindly identify which mod is causing the problem

**Comment by ShikyoKira** [comment]
No update on this issue for more than a month. Closed
