### ISSUE TITLE
Invisible character model with XP32

### ISSUE THREAD

**Issue by DroidZed** [ShikyoKira/Project-New-Reign---Nemesis-Main#169]
Hi, I'm having this weird character invisibility bug that happens sometimes.
The thing is my character's model is gone and when I jump in 3rd person I see my weapon floating in the ground.
The 1st person rendering is fine but I have issues with the 3rd person.
I hope you can help me here and thanks !

Ps  : this is the 3rd time happening , the first one is like this one and I manged to do it by reinstalling XP32 (I think the issue is Nemesis PCEA mod because of the new animations).
The second one is when I ready my weapon, sometimes I turn invisible when I turn left and then my character turns back when I turn right (Idk what's happening here).

**Comment by ShikyoKira** [comment]
you got a video of it? this is the first time i receive such report

**Comment by DroidZed** [comment]
For that I have to replicate the bug, but now after removing PCEA I think the issue has been fixed.
If run into the same problem I'll send you the video right away.

**Comment by ShikyoKira** [comment]
i'll close this issue then. Open it up again if you run into it again
