### ISSUE TITLE
Error 1056

### ISSUE THREAD

**Issue by Jedib1** [ShikyoKira/Project-New-Reign---Nemesis-Main#170]
Hello there, I was attempting to run Nemesis for the first time and I get this error whenever Nemesis is attempting to load animations from mod folders in Skyrim Special Edition\Data\meshes\actors\character\animations

ERROR(1056): Invalid element. Only "F" "L", or digit is acceptable as input element. Please contact the template creator
Template: b
File: #0110
Line: 23
Option: b[][B]

It seems to happen no matter the mod that animations are being loaded from, as adding them and removing them, so long as one is there, changes nothing. I have tried multiple fresh downloads and reinstalls of Nemesis to no avail.  

My Version Code is 2445-2708 and I have attached my UpdateLog and PatchLog below:

[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4356337/UpdateLog.txt)
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4356338/PatchLog.txt)

---

Edit: 
It appears to be present no matter the install method, and I have attempted installing older versions and then updating them to no avail. Restarts have no impact on it. I have made sure that I am using the SSE version.

**Comment by Jedib1** [comment]
It appears to be present no matter the install method, and I have attempted installing older versions and then updating them to no avail. Restarts have no impact on it. I have made sure that I am using the SSE version.

**Comment by ShikyoKira** [comment]
Yup. I have noted this issue and fixed it in devs version. Thanks for the report still

**Comment by Haiyama** [comment]
Follow this, having the same problem

**Comment by tectonicLeader** [comment]
for skyrim SE
ERROR(1056): Invalid element. Only "F" "L", or digit is acceptable as input element. Please contact the template creator
Template: o
File: #0110
Line: 55
Option: o[][B]

**Comment by wolverinemegzi** [comment]
here in 2021 still having this issue 

ERROR(1056): Invalid element. Only "F" "L", or digit is acceptable as input element. Please contact the template creator
Template: b
File: #0110
Line: 23
Option: b[][B]
using SSE version
