### ISSUE TITLE
Critical Hit Animation

### ISSUE THREAD

**Issue by Consaliette** [ShikyoKira/Project-New-Reign---Nemesis-Main#174]
Critical Hit - Backstab and Parry in Skyrim
https://www.nexusmods.com/skyrim/mods/90897
parry/backstab animations does not work.

Nemesis version: Nemesis.Unlimited.Behavior.Engine.v0.83c-beta.rar
Steps to reproduce:
-install mod
-update engine through Nemesis and Launch Nemesis Engine
-play game with default mod's options

It seems like some problems with syntax FNIS_CriticalHit_List.txt:
_WARNING(1026): Invalid option
File: FNIS_CriticalHit_List.txt
Line: 3
Option: Tn_
Also PatchLog and UpdateLog:

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4363332/PatchLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4363333/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
Ignore the warning messages. They definitely are not the one causing it

Are you using FNIS? is the output of Nemesis being overwritten by other mods?

**Comment by Consaliette** [comment]
1. FNIS installed but disabled. FNIS output remove completely.
2. No, Nemesis/Nemesis output are in the bottom of MO2 modlist (left pane). Also it's almost vanilla test's profile with minimum mod.
If that can help here are the screenshots of MO2.
https://imgur.com/a/5kmlH8Z

**Comment by ShikyoKira** [comment]
u got video of it? or can you describe how it doesn't work?

**Comment by Consaliette** [comment]
Better to describe.
During the battle, an animation trigger with sound is triggered, the camera, as expected, switches to the 3rd person view, however, the parry animation does not play. Damage to the NPCs, respectively, is also not applied.
The MO console and log do not show anything suspicious.

**Comment by Consaliette** [comment]
Video:
https://youtu.be/sVkFAyejJP4

**Comment by ShikyoKira** [comment]
alright. I'll give it a test here

**Comment by Consaliette** [comment]
Thanks.

**Comment by ShikyoKira** [comment]
ok. tested it. it works for me. But not all the time. This could be due to too many scripts. Same goes for backstab. From the comment section of the mod page, there was a talk about its consistency. I fought a 3k hp bandit just to try it. Keep spamming parry whenever power attack comes at you. Sometimes it triggers sometimes don't

**Comment by Consaliette** [comment]
Well ok, thanks for testing. Then i close the issue.
