### ISSUE TITLE
Attack speed of double holding dagger is very slow

### ISSUE THREAD

**Issue by zmzjeff886** [ShikyoKira/Project-New-Reign---Nemesis-Main#175]
Attack speed of double holding dagger is very slow
Please fix it!

**Comment by zmzjeff886** [comment]
Sorry, my English is not good.
Accurately speaking, the third person animation of double dagger power attack(windmill attack) is very slow,Dual holding perk not work.

**Comment by ShikyoKira** [comment]
thanks for the report. I have noted the issue. It is instead as you said. Will fix it in next update. In the meantime, you can fix it yourself by delete this file `data/nemesis_engine/mod/nemesis/#2976.txt`
