### ISSUE TITLE
Tpose  

### ISSUE THREAD

**Issue by jojoerc** [ShikyoKira/Project-New-Reign---Nemesis-Main#176]
im getting T pose problems when using CGO and Nemesis . Here is patch and update log.
Also im using Nexus mod manager
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4365055/UpdateLog.txt)

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4365053/PatchLog.txt)

**Comment by xFrosty7** [comment]
i'm using them both aswell and i don't have a T pose, make sure you enable the CGO patch in nemesis and see if that works. if it doesn't, there's probably something wrong in your load order.
i also highly recommend switching over to mod organizer 2 if you can, it will save you a LOT of time and frustration.

**Comment by ShikyoKira** [comment]
yes. its better to use MO2, as its hard to know your load order. Install CGO, and then run Nemesis, enable CGO patch

**Comment by jojoerc** [comment]
i think the problem is with CGO , nemesis is ok. still dont know what the problem is
using MO2

**Comment by NamorNilugar** [comment]
im tried using CGO+PCE0.8+360Movement Behavior1.3.1 with Zaz pack and other LL mods with 10k animations, and all work great(MO 1.4),  but one time after update Behavior files, animations was broken and  I had to replace generated 0_master.hkx to original file, and now it work again, try do it, sorry eng not my native language

**Comment by NamorNilugar** [comment]
> i think the problem is with CGO , nemesis is ok. still dont know what the problem is
> using MO2

im tried using CGO+PCE0.8+360Movement Behavior1.3.1 with Zaz pack and other LL mods with 10k animations, and all work great(MO 1.4),  but one time after update Behavior files, animations was broken and  I had to replace generated 0_master.hkx to original file, and now it work again, try do it, sorry eng not my native language

**Comment by jojoerc** [comment]
Ok I will try it , but how to get the original 0_master.hkx from , plus i
use only CGO , xpmse and nemesis pcae2

**Comment by NamorNilugar** [comment]
[Data.zip](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4369795/Data.zip)

**Comment by jojoerc** [comment]
Thanks i will test and reply

**Comment by jojoerc** [comment]
Nope , it is not working

**Comment by ShikyoKira** [comment]
thanks for the confirmation. I'll close this issue now
