### ISSUE TITLE
CTD or idle slide bug when animation count goes over a certain threshold

### ISSUE THREAD

**Issue by melona012** [ShikyoKira/Project-New-Reign---Nemesis-Main#178]
This issue is not like 'serious' crash problem because I can just detour it by deleting some files,
but I just wanted to let you know that two .txt files that Nemesis generates in \meshes (animationdatasinglefile.txt, animationsetdatasinglefile.txt) cause Creation Kit SE to crash on launch.
If I delete those two, no problem occurs. and I can simply regenerate two files through Nemesis after using CK, so as you see it's not that big problem, but I was curious how .txt can cause issues

**Comment by ShikyoKira** [comment]
ah you must have gone above 10k animations. Even if it doesn't crash your CK, it likely will crash your skyrim or glitch the animation. I have fixed that in devs version. Thanks for your report still

**Comment by Pop000100** [comment]
How does fnis allow over 10k animations then?

**Comment by ShikyoKira** [comment]
> I have fixed that in devs version
this ^

**Comment by Consaliette** [comment]
Sorry but where can I get _devs version_? Or do you mean compiling it by myself? Thanks.

**Comment by Pop000100** [comment]
what is the new limit?

**Comment by badbonez** [comment]
> Sorry but where can I get _devs version_? Or do you mean compiling it by myself? Thanks.

^This.  How can we get the fix to this issue?

**Comment by ShikyoKira** [comment]
fixing this require you to modify the current templates. Let me do that

> Sorry but where can I get devs version? Or do you mean compiling it by myself? Thanks.
I don't recommend. The code changes daily, even tho someday i don't push the changes to github. If you insist getting the templates, try go to `test environment/behavior templates` get everything there and the 1 in your local machine. Be sure to make a backup as I'm not sure if released version is capable of running these newly modified templates

**Comment by Consaliette** [comment]
> I don't recommend.
So basically there is no way to use fixed version for _average_ user then. And with 
Animation Limit Crash Fix LE
https://www.nexusmods.com/skyrim/mods/100672
many users can install more animation packs (include posers and other stuff). And now we must choose: use them all with FNIS but without combat mods (TUDM+TUDM Reanimated, Stagger on Hit, CGO+) or using those combat mods, but without dozens of screenarchery related packs. 
May be there are way to upload  more pre release versions of Nemesis with proper tags and description to github? Not every day or even week of course, but at least 1 every month?

**Comment by badbonez** [comment]
So I came to the same conclusion and have come up with a hybrid FNIS/Nemesis load.  I use Mod Organizer 2 so it makes it pretty simple.  I have a main mod where I run the game from, it has all the mods with animations like Leito/ZaZ/Flower Girls, etc. and I have the Crash Limit patch loaded.  I run FNIS from there.  In  a second profile I have ONLY Nemesis, Nemesis PCEA and those mods that require Nemesis.  Right now it's only 760 animations.  After I run FNIS in the main mod profile, I go to this second profile and run Nemesis from there.  I return to my main profile and run the game. 

Warning: This may not work in the long run.  I have not played much, but so far I have all the Nemesis animations like Combat Gameplay Overhaul working and I've seen a few of the older mod's animations working as well.  Sexy Moves is working too.  I don't know if this would work for you but I thought I would mention it.
