### ISSUE TITLE
Error 1207 failed to output xml

### ISSUE THREAD

**Issue by willhedi** [ShikyoKira/Project-New-Reign---Nemesis-Main#179]
ERROR(1207): Failed to output xml file. Please ensure that the hkx file is readable and valid by contacting the mod author.
Here the Patchlog
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4373083/PatchLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4373085/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
I suspect said file is in 64bit, which isn't compatible with your skyrim version. Please double check that file

**Comment by willhedi** [comment]
which file i must check you know im little bit confused

**Comment by ShikyoKira** [comment]
`d:\game\the elder scrolls v skyrim - legendary edition\data\meshes\actors\character\Character Assets Female\skeleton_female.hkx`

**Comment by ShikyoKira** [comment]
Duplicate of #173
