### ISSUE TITLE
Error 1190

### ISSUE THREAD

**Issue by ShiroXIII** [ShikyoKira/Project-New-Reign---Nemesis-Main#181]
Whenever I try updating the engine I get this error-on an clean install of Nemesis too.

Initializing engine update

ERROR(1190): Missing state machine info node detected. Please contact the mod author
Mod: dscgo
ID: #0505
State Machine Info Node: #dscgo$161

Failed to update engine

**Comment by ShikyoKira** [comment]
reinstall dscgo or inform the mod author not me. I will open this issue back if even the mod author has no idea what it is
