### ISSUE TITLE
Error(2006): Missing behavior file

### ISSUE THREAD

**Issue by Raysayvose** [ShikyoKira/Project-New-Reign---Nemesis-Main#182]
Not sure what its on about, i couldn't manage to find any such file in nemesis anywhere, unless the \ is noting 2 separate files or i wasn't looking in the right places but i cant be sure and dont want to just go renaming any file that feels like it
----------------------------
Initializing engine update

ERROR(2006): Missing behavior file. The behavior file name must be in this format ("Nemesis_<file name>.xml") and it must located in the same path as the hkx counterpart. Please contact the mod author
File: _1stperson\1hm_behavior

Failed to update engine
----------------------------
some help would be much appreciated.
please and thank you

**Comment by ShikyoKira** [comment]
you didn't seem to install it correctly. download the files from release page not the main code page
