### ISSUE TITLE
Reopening Error(3024) getting issue after fix

### ISSUE THREAD

**Issue by Raysayvose** [ShikyoKira/Project-New-Reign---Nemesis-Main#183]
I recognized that this was solved previously but for some reason I'm still receiving the error and i'm unable update the engine

Initializing engine update

ERROR(3024): Duplicated header has been detected in "animationdatasinglefile.txt". Please contact the template creator
Template: behavior templates\__folder_managed_by_vortex
Project: <2>
Header: <3>

Failed to update engine

are we still not allowed to use Vortex?

Help would be much appreciated, please and thank you

**Comment by ShikyoKira** [comment]
yup i am certain it has been fixed. Redownload the latest version and test again

**Comment by Raysayvose** [comment]
it was my bad, i had to completely delete all my animations and require them, uninstalling my mods didn't do the trick but it works flawlessly now thank you for making this system
