### ISSUE TITLE
Link to "GunMod" in GUI is invalid

### ISSUE THREAD

**Issue by DBHHeroesJojy** [ShikyoKira/Project-New-Reign---Nemesis-Main#184]
I apologize if this isn't the place for this, or if this is already know, but the "GunMod" listed in the Nemesis GUI has it's link set to "https://discordapp.com/channels/@me/654625642230317066", which is a private message, Only the person who recieved that message can actually follow the link. I've tried to find the mod based on the given author name, DeclineDawn, with no success.

**Comment by ShikyoKira** [comment]
sadly this is the file i was given by him. and it is supposed to fix by the author. I can only help you inform him thats all.

Since this isn't Nemesis' issue, i'll be closing this issue. Thanks for the report
