### ISSUE TITLE
Always getting CTD right before Bethesda Logo

### ISSUE THREAD

**Issue by OneChanceMan** [ShikyoKira/Project-New-Reign---Nemesis-Main#185]
I tried SSE version with MO2.
I always get CTD before Bethesda logo shows up.
I finished Updating Engine(took 12-13sec, too short?), and Running Engine.
By the way, I've been stuck on 100% while running engine, so I unchecked XPMSSE on MO2 (several thread I read said so). Then I rechecked it after that.
But I couldn't get to familiar logo after all.
I'm using 16k+ animations, but I'm not sure it's within limit or not. I can't find any articles or thread mentions about it.

**Comment by ShikyoKira** [comment]
Duplicate of #178

**Comment by OneChanceMan** [comment]
Thank you for replying!
Understood. 
I'm looking forward to further development.
Keep doing great work and take care yourself.
