### ISSUE TITLE
Warning (1031), (1003) + CBP physics crash log 

### ISSUE THREAD

**Issue by Sanitatem** [ShikyoKira/Project-New-Reign---Nemesis-Main#186]
I have a warning count of 6037, most of which come from warning 1031 which are various:

WARNING(1013): Animation has not been registered in defaultmale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\bow_unequip.hkx

I have also attached a cbp error log. I experienced CTD during a siege in The Second Great War Mod. 

Please let me know if I need to upload anything else! 

[cbp.log](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4396142/cbp.log)
[Warning check.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4396143/Warning.check.txt)

**Comment by ShikyoKira** [comment]
`IGNORE THE WARNING MESSAGE(S) IF YOU ARE NOT THE MOD AUTHOR. IT IS FOR DEBUGGING PURPOSES`
as stated in the warning check log. Warning occurs when you are the mod author and you know what you are doing or the user did something wrong. In other words, should never be brought up. You can report the symptoms of your problem, unless being asked for it. These warnings mean nothing
Nemesis will not cause ctd once u have successfully loaded it in game. It will only make your character freeze if it fails

**Comment by Sanitatem** [comment]
Ok, I guess I must have messed something up in the installation, because I hadn't had issues with CBP physics before. Thanks!

**Comment by Sunconure11** [comment]
How did you resolve this? I'm having something similar, but I'm not using CBP. Basically, I'm getting a CTD related to the default male file.
