### ISSUE TITLE
Nemesis and ZaZ Animation Pack

### ISSUE THREAD

**Issue by badbonez** [ShikyoKira/Project-New-Reign---Nemesis-Main#190]
I am having an issue when I install Zaz Animation Pack (https://www.loverslab.com/files/file/5957-zaz-animation-packs-for-se/) and then run Nemesis, in game the characters are frozen, only moving by skating.  This only happens with this pack loaded, other animation packs, such as Funnybizness, work just fine. Or at least do not cause this issue.  Several other mods require this animation pack to work. Is it possible to use the PCEA folder for the animations?  And if so, how would that work?  Or is there a way to get these animations to work with Nemesis.   Thank you!

**Comment by RowdyRamen** [comment]
How many animations do you have? I think there is an issue where if you go over 10k animations the game either ctd's or walking animations freeze

**Comment by badbonez** [comment]
> How many animations do you have? I think there is an issue where if you go over 10k animations the game either ctd's or walking animations freeze

Less than 10K, somewhere around 7k.  But I think I have erred. I created a game with just nemesis and the Zaz animation pack and the animations seemed to work as expected.  So something else is causing this. But it's strange as the same load order and mods work fine with FNIS.  Anyway, closing this.
