### ISSUE TITLE
Nemesis giving false positive reports

### ISSUE THREAD

**Issue by cygarniczka** [ShikyoKira/Project-New-Reign---Nemesis-Main#191]
I ran Nemesis after emptying it output folder it gave error that I should report here. After second run it generated behavior files correctly.

> ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
> File: C:\Users\Cygar\AppData\Local\Nemesis\Nemesis_AA_Core.pex
> Message: boost::filesystem::remove: The process cannot access the file because it is being used by another process: "C:\Users\Cygar\AppData\Local\Nemesis\Nemesis_AA_Core.pex"
> 
> Failed to generate behavior

I don't use Nemesis PCEA. I use:
Combat behavior improved (SSE version)
Enhanced Combat Behaviors
The Ultimate Dodge Mod
Animated Armory
Go To Bed

that's all mods that influence the behavior files.

**Comment by ShikyoKira** [comment]
AA is not PCEA. Animated Armoury uses AA system so yes. This is correct. Tho this specific error regarding remove has been addressed in devs version
