### ISSUE TITLE
Sprinting animation plays too fast

### ISSUE THREAD

**Issue by SirojDart** [ShikyoKira/Project-New-Reign---Nemesis-Main#192]
First of all, hello guys! Since this is my first post I'm not really familiar with all of this.

So I've been playing and modding Skyrim since release on a potato. A week ago the mod "Combat Gameplay Overhaul" dropped on the Nexus hence I swapped from using FNIS to Nemesis. I've been using Dragonfly's TBBP animations as my go to for years now (except the idle bc... Well if you know the animation you also know why everyone hates it) and I never had a problem. But since I'm using Nemesis the sprint animation isn't playing properly anymore. It looks like it's going way too fast. However, walking and running are working as intended. 
As a somewhat experienced modder I'm at a loss on what to do. Help is very much appreciated! 

I'm using Vortex to install and manage mods, UNP body, and the HDT skeleton from XPMSE. Also I had LOOT sort my load order with no changes to it. 

If you need my mods I'll gladly share them if you tell me how to do it without me writing everything by hand. (currently running 185 mods)

Load order: 
  0  0     Skyrim.esm
  1  1     Update.esm
  2  2     Dawnguard.esm
  3  3     HearthFires.esm
  4  4     Dragonborn.esm
  5  5     Unofficial Skyrim Legendary Edition Patch.esp
  6  6     Skyrim Project Optimization - Full Version.esm
  7  7     EFFCore.esm
  8  8     hdtHighHeel.esm
  9  9     Heels Sound.esm
 10  a     Skyrim Supplemental Patch.esp
 11  b     RaceCompatibility.esm
           HighResTexturePack01.esp
           HighResTexturePack02.esp
           HighResTexturePack03.esp
 12  c     No Magic Ninja Dodge - No DLC.esp
 13  d     XPMSE.esp
 14  e     SkyUI.esp
 15  f     Dual Sheath Redux.esp
 16 10     Cassandra Apocrypha Robes UNP LE.esp
 17 11     Demon Armor UNP LE.esp
 18 12     RaceMenuMorphsUUNP.esp
 19 13     Neithteam Warpaint.esp
 20 14     SignatureEquipment.esp
 21 15     Radzig - Johnskyrim.esp
 22 16     NB-Scars.esp
 23 17     Solaze.esp
 24 18     DM BDOR Karlstein by Team TAL.esp
 25 19     SkyHUD.esp
 26 1a     BDOR Mueburus by Team TAL.esp
 27 1b     Nemesis PCEA.esp
 28 1c     UIExtensions.esp
 29 1d     Beards.esp
 30 1e     bearmusicianeng.esp
 31 1f     yurica_kimono.esp
 32 20     12FemaleBrows.esp
 33 21     Relationship Dialogue Overhaul.esp
 34 22     3DNPC.esp
 35 23     DX Witcher Armor.esp
 36 24     Hothtrooper44_ArmorCompilation.esp
 37 25     Immersive Weapons.esp
 38 26     Realm of Lorkhan - Custom Alternate Start - Choose your own adventure.esp
 39 27     Reliquary of Myth.esp
 40 28     The Brotherhood of Old.esp
 41 29     Further Dark Dungeons for ENB.esp
 42 2a     Inigo.esp
 43 2b     Guards_Armor_Replacer.esp
 44 2c     Atlas Legendary.esp
 45 2d     Crimson Blood Armor.esp
 46 2e     DIS_Armor_Fractions.esp
 47 2f     Unique Uniques.esp
 48 30     Armored Circlets.esp
 49 31     Regent.esp
 50 32     TreasureHunterGarb.esp
 51 33     chfshPlayerVoicesets.esp
 52 34     CROSS_Crucible.esp
 53 35     DX Druid Armor.esp
 54 36     Celes Nightingale Armor.esp
 55 37     Spartan Bard Outfit UNP LE.esp
 56 38     Bijin AIO.esp
 57 39     TheAmazingWorldOfBikiniArmor.esp
 58 3a     Citizens.esp
 59 3b     CitizensII.esp
 60 3c     Immersive Citizens - AI Overhaul Lite.esp
 61 3d     Ursine Armour.esp
 62 3e     Aeonbarr V2.1.esp
 63 3f     Godswords - Johnskyrim.esp
 64 40     Lucien.esp
 65 41     Cataract.esp
 66 42     Faction Crossbows.esp
 67 43     ColdharbourDaedra.esp
 68 44     ArtifactsOfBoethiah.esp
 69 45     ArtifactsOfNocturnal.esp
 70 46     Balanced_Magic.esp
 71 47     FleshFX.esp
 72 48     EFFDialogue.esp
 73 49     PAN_FollowerPack1.esp
 74 4a     Equipping Overhaul.esp
 75 4b     DragonboneBarbarianArmor.esp
 76 4c     DSerCombatGameplayOverhaul.esp
 77 4d     Imperious - Races of Skyrim.esp
 78 4e     Unarmed Scaling.esp
 79 4f     XCEx.esp
 80 50     DragonboneBarbarianMale.esp
 81 51     Greatsword.esp
 82 52     Daedric Reaper Armor.esp
 83 53     Anchor - Johnskyrim.esp
 84 54     Atlas Compass Tweaks.esp
 85 55     Auto Unequip Ammo.esp
 86 56     Balanced_Magic_Dawnguard.esp
 87 57     BHWarPaints.esp
 88 58     Bijin NPCs.esp
 89 59     Bijin Warmaidens.esp
 90 5a     Bijin Wives.esp
 91 5b     Bloody Scythe and Soulrender Reborne.esp
 92 5c     dD - Enhanced Blood Main.esp
 93 5d     dD - Realistic Ragdoll Force - High.esp
 94 5e     dD - Realistic Ragdoll Force - Medium.esp
 95 5f     dD - Realistic Ragdoll Force - Realistic.esp
 96 60     dD - Realistic Ragdoll Force - Reduced.esp
 97 61     dD-Dragonborn-Dawnguard-EBT Patch.esp
 98 62     dD-Medium Script Range.esp
 99 63     dD-Reduced Splatter Size.esp
100 64     dD-Reduced Wound Size.esp
101 65     Facelight.esp
102 66     FreckleMania2.esp
103 67     GirlHeavyArmor.esp
104 68     HelmetToggle.esp
105 69     Hothtrooper44_Armor_Ecksstra.esp
106 6a     Improved Dragon Shouts.esp
107 6b     Improved Dragon Shouts - Dawnguard.esp
108 6c     Improved Dragon Shouts - Dragonborn.esp
109 6d     Lamp.esp
110 6e     Maevan2EyeBrows.esp
111 6f     RaceCompatibilityUSKPOverride.esp
112 70     RaceMenu.esp
113 71     RaceMenuPlugin.esp
114 72     Serana.esp
115 73     SGEyebrows.esp
116 74     Sheps_Tattoo_Collection.esp
117 75     SMIM-DragonbornTernFix.esp
118 76     SMIM-DungeonsCliffsIceSkirts.esp
119 77     SMIM-FarmhouseFlickeringFix.esp
120 78     StormcloakHeroGear.esp
121 79     TheEyesOfBeauty.esp
122 7a     TMSG.esp
123 7b     TMSG0Z.esp
124 7c     TW3Eyes.esp
125 7d     WetandCold.esp
126 7e     WetandCold - Ashes.esp
127 7f     WetandCold - EO patch.esp
128 80     yurica_chevaleresse_II [HDT].esp
129 81     Brows.esp
130 82     Andromeda - Unique Standing Stones of Skyrim.esp
131 83     AddItemMenuLE.esp
132 84     UltimateCombat.esp
133 85     UltimateCombatSekiro.esp
134 86     KS Hairdo's.esp
135 87     PAN_NPCs.esp
136 88     PAN_NPCs_DG.esp
137 89     StrangeRunes.esp
138 8a     manny_eyeglasses.esp
139 8b     Unleveled_Items.esp
140 8c     YOT - Your Own Thoughts.esp
141 8d     Fudou Myouou.esp
142 8e     Sugaruya Katana.esp
143 8f     DaggerCraft.esp
144 90     FranklyHDImperialArmorsAndWeapons.esp
145 91     Ulags Legacy.esp
146 92     Perks from Questing.esp
147 93     RoM + Unique Uniques Patch.esp
148 94     Ordinator - Perks of Skyrim.esp
149 95     Dual Sheath Redux Patch.esp

 

Note: This is an exact copy of my LL/Nexus forums entries.

**Comment by ShikyoKira** [comment]
Nemesis doesn't change sprint animation. Please refer this to author of mods that have changed sprint animation. My guess is CGO but could be something else too. Before you do that, strip off all the unrelated mods before you make a report to him. Have a minimal setup that is capable of recreating the same issue. I'll close this issue as it is unrelated to nemesis. Thanks for reporting
