### ISSUE TITLE
Random T posing with CGO, no FNIS

### ISSUE THREAD

**Issue by dankkushbonger** [ShikyoKira/Project-New-Reign---Nemesis-Main#193]
All animations work properly, but my character sometimes T poses for a few seconds. I went through other issues posted here and it might be a lag of some sort. How can I fix this or at least reduce T posing to absolute minimum?

I'm not using FNIS and I don't have the insertAttackData.dll in my Skse>Plugins folder. I completely deleted all behaviour files added by mods before manually installing Nemesis and then CGO. Sorry if I'm posting in the wrong place, but I've been trying to solve this problem for days.

**Comment by ShikyoKira** [comment]
do those t-poses happen for a few secs and then recover back to normal? Does it only happen when you change animation, for example, idle > jump or even while idling it still suddenly t-pose for seemingly no reason?

**Comment by dankkushbonger** [comment]
They happen for a few seconds and then recover back to normal. It happens when running and attacking. Dodging or jumping when I T pose immediately plays the right doge/jump animation. They don't happen when I'm idle. Running, jumping or dodging with my weapon sheathed works normally. Running when I'm T posing doesn't stop the T pose.
They usually happen with greatswords or when I change the grip and hold a 1h weapon (vanilla or modded) in two hands. Regular 1h animations work fine even when used with 2h weapons, although I can very rarely get a T pose for a split second. I couldn't find out what exactly causes this to happen, sometimes I can sprint for miles and clear bandit camps without any issues, sometimes moving a few inches makes me T pose.
Removing the cloak spell that adds this ability to NPCs didn't help, and only one other person reported this issue on the CGO mod page.
Removing any modded animation replacers (files what don't have esp) didn't help. I don't have any other animation/combat mods installed or mods that require Nemesis, most of them are item mods.
I installed Nemesis, then CGO, ran Nemesis, checked the mod on the list, updated and then launched the  behaviour engine. It didn't show any errors and after its finished it says "0 animation(s)". I hope I gave at least some useful info, this never happened to me with animation or behaviour mods.

**Comment by ShikyoKira** [comment]
I'll inform DServant about this matter

**Comment by dankkushbonger** [comment]
They're all from CGO, I didn't replace or modify them. The animations are running with a 2h sword, attacking with a 2h sword. 2h sword animations are also applied to 1h weapons when I change grip, and that's when random t-poses happen. It happens only when I'm holding a 2h sword, running with a sheathed weapon is fine. Running/idling with a sheathed weapon is vanilla.

It doesn't always happen when I change animation. For example I can run with a 2h sword into a group of enemies and my character will t-pose before I'll attack/dodge/change running direction. So it can happen when I'm using the same animation.

**Comment by ShikyoKira** [comment]
Ok, it kinda confirm that this is CGO's side issue. DServant needs to cache these animations in `animationsetdatasinglefile.txt` to prevent them from t-pose. This is something out of nemesis scope. Thanks for clarifying
