### ISSUE TITLE
error 5005 while updating.

### ISSUE THREAD

**Issue by biboo2** [ShikyoKira/Project-New-Reign---Nemesis-Main#194]
ERROR(5005): BUG FOUND!! Report to Nemesis' author immediately
File: temp_behaviors\animationsetdatasinglefile.txt
Line: 74613.
I tried reinstalling, but doesn't work.

**Comment by ShikyoKira** [comment]
send me your data/nemesis_engine/temp_behaviors/animationsetdatasinglefile.txt

**Comment by biboo2** [comment]
Well, now it works, I don't understand why it didn't work before because I just installed it like other times. I'm sorry to have lost your time and thank you for your mod !
