### ISSUE TITLE
WARNING(1013) & no one attack animation not working

### ISSUE THREAD

**Issue by KYLHACKER** [ShikyoKira/Project-New-Reign---Nemesis-Main#196]
WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_runright.hkx

WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_runstrafeleft.hkx

WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_runstraferight.hkx

WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_walkbackward.hkx

I have warning 1013 in all attack and walk animation, and only idle animation work properly. Also trying to attack mudcrab, and he didn't use animations.

**Comment by ShikyoKira** [comment]
Reinstall nemesis. Warning is a sign that the problem is very likely to be on your side

**Comment by ShikyoKira** [comment]
Duplicate of #180
