### ISSUE TITLE
Nemesis Crashes Updating the engine on the same time

### ISSUE THREAD

**Issue by shuritox** [ShikyoKira/Project-New-Reign---Nemesis-Main#198]
Hi,

When you try to run it the first time, it just closes in 3%

This is the log:

```
[2020-Apr-10 18:43:29] Nemesis Behavior Version: v0.83b
[2020-Apr-10 18:43:29] Current Directory: D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Nemesis_Engine
[2020-Apr-10 18:43:29] Data Directory: D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\
[2020-Apr-10 18:43:29] Skyrim Special Edition: TRUE
[2020-Apr-10 18:43:29] Detecting processes...
[2020-Apr-10 18:43:30] Process count: 32
[2020-Apr-10 18:43:30] Initializing file check...
[2020-Apr-10 18:43:30] File Check complete
[2020-Apr-10 18:43:30] External script run complete
[2020-Apr-10 18:43:30] Temp behavior clearance complete
[2020-Apr-10 18:43:30] Data record complete
[2020-Apr-10 18:43:30] New Animations extraction start (Folder: behavior templates\b\animationdatasinglefile)
[2020-Apr-10 18:43:30] New Animations extraction complete (Folder: behavior templates\b\animationdatasinglefile)
[2020-Apr-10 18:43:30] New Animations extraction start (Folder: behavior templates\b\behavior)
```

Aparently the problem exists when the engine update is proccesing files started with "#"

**Comment by ShikyoKira** [comment]
What are the symptoms you see when the crashing occur?

**Comment by shuritox** [comment]
hmmm i should clarify;
 it wasn't a crash, but a close.

so basically the app just close at 3%
and never completes the engine creation

**Comment by nhimah** [comment]
I am also having the same issue.

[2020-Apr-12 19:11:33] Nemesis Behavior Version: v0.83b
[2020-Apr-12 19:11:33] Current Directory: E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Nemesis_Engine
[2020-Apr-12 19:11:33] Data Directory: E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\
[2020-Apr-12 19:11:33] Skyrim Special Edition: TRUE
[2020-Apr-12 19:11:33] Detecting processes...
[2020-Apr-12 19:11:33] Process count: 32
[2020-Apr-12 19:11:33] Initializing file check...
[2020-Apr-12 19:11:33] File Check complete
[2020-Apr-12 19:11:33] External script run complete
[2020-Apr-12 19:11:33] Temp behavior clearance complete
[2020-Apr-12 19:11:33] Data record complete
[2020-Apr-12 19:11:33] New Animations extraction start (Folder: behavior templates\b\animationdatasinglefile)
[2020-Apr-12 19:11:33] New Animations extraction complete (Folder: behavior templates\b\animationdatasinglefile)
[2020-Apr-12 19:11:33] New Animations extraction start (Folder: behavior templates\b\behavior)

**Comment by TMLKyza** [comment]
Having a similar issue the only difference is that the update stops at 1% and no UpdateLog.txt is created.

I'm attaching the logs here

[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4469043/CriticalLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4469045/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
> I have the same problem when updating the engine. It crash at 70% - 79%-ish. But I just found out that my nemesis engine got overwrited by some files in the Overwrite tab at the bottom of the left panel .So I move all of the files in the overwrite folder in mod organizer folder to another folder. And BOOM! Works flawlessly. Hope this work for u too.

Just found someone has a possible solution to this. Give this a try

**Comment by avovom** [comment]
Hey, I have the same problem where launching nemesis is fine, but clicking the update engine button causes a crash. My crash happens at 2% usually, sometimes it gets a little farther to 3%, one time it made it to 12%. The crash presents as a windows crash, where a windows window pops up saying that nemesis unlimited behavior engine has encountered a problem and then a second window appears after a bit that says "nemesis unlimited behavior engine.exe has stopped working" and then the program closes. I tested it on an MO2 profile without any mods, and there was no crash, the program ran successfully and everything. I've got 255 plugins, and maybe 270 odd mods installed on the profile that crashes. I've also tried it with an entirely separate set up installed on a separate drive that has a high number of mods as well, and the crash replicates at 2% again. Both mod setups are completely stable as well, they've been tested for hundreds of hours on each. I've attached logs here. 

I also tried to do the solution you posted where you move files out of the overwrite tab at the bottom of MO2's left panel, and it didn't make a difference, it kept crashing the same as before. Thanks for making such a great tool, and hoping this can be an easy fix!

[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4484217/CriticalLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4484218/UpdateLog.txt)

**Comment by sabinoplane** [comment]
Same problem here, i did my best to follow all the instructions correctly but whenever i try to update the engine it just closes
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4497033/CriticalLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4497034/UpdateLog.txt)
So i tested and apparently it only happens when i launch it through vortex, if i launch it through the folder it runs fine

**Comment by shuritox** [comment]
> > I have the same problem when updating the engine. It crash at 70% - 79%-ish. But I just found out that my nemesis engine got overwrited by some files in the Overwrite tab at the bottom of the left panel .So I move all of the files in the overwrite folder in mod organizer folder to another folder. And BOOM! Works flawlessly. Hope this work for u too.
> 
> Just found someone has a possible solution to this. Give this a try

Tested it, and now is working! thanks

**Comment by TheCreeperBoy45** [comment]
I have been trying to update the nemesis engine through the data folder launcher and it keeps closing between 2% and 12%. My mods are through vortex while Nemesis was downloaded manually into the data folder
The update runs up until it hits behavior **templates\b\behavior**. then it closes.
Is there a solution to this or is the problem related to Vortex somehow?

**Comment by TheCreeperBoy45** [comment]
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4634659/UpdateLog.txt)

**Comment by Xanfer** [comment]
I had this issue too the other day after installing a few mods for the first time and setting up nemesis. 
Worked perfect the first time updating than the closure at like 12% any other time.
I turned off my PC and went to sleep, and after work tried again and updated perfectly (have not tried updating it again since then)
Maybe vortex, or other applications are causing issues that a fresh reboot fixes? I plan on trying it again to see if it is consistent when i add more mods later.

**Comment by alekulyn** [comment]
I'm aware that this has been closed, but I've clean the FNIS output, overwrite files, disabling every mod but Nemesis PCEA, rebooting, and etc. It still crashes around 4%. I've also been looking for a verbosity switch in the settings and documentation, but haven't been able to find one.

[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5192104/UpdateLog.txt)

**Comment by lbotticchio** [comment]
At the risk of necro'ing a dead thread I had this issue and resolved it.  I went back to my Skyrim SE LO and updated it and went to rerun Nemesis. When I updated the Engine it would crash at 2%. Poking around in my Nemesis_Engine directory I noticed that the Skyrim Data folder location in the nemesis.ini file was wrong. Once I put in the correct location it worked (Through MO2) with no issues! Hope this helps someone.

**Comment by electrofamily** [comment]
I figured it out: Copy the "meshes, Nemesis_Engine and scripts folders" out of the Nemesis.Unlimited.Behavior.Engine.-beta" folder and paste them into the Skyrim Data folder. If you have a folder called Nemesis in your data folder, delete that one first. Those first three folders need to be copied/merged into the Skyrim data folder (not inside of another folder). Thanks and shine on.

**Comment by electrofamily** [comment]
> I'm aware that this has been closed, but I've cleaned the FNIS output, overwrite files, disabling every mod but Nemesis PCEA, rebooting, and etc. It still crashes around 4%. I've also been looking for a verbosity switch in the settings and documentation, but haven't been able to find one.
> 
> [UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5192104/UpdateLog.txt)

It's likely a folder conflict: Copy the "meshes, Nemesis_Engine and scripts folders" out of the Nemesis.Unlimited.Behavior.Engine.-beta" folder and paste them into the Skyrim Data folder. If you have a folder called Nemesis in your data folder, delete that one first. Those first three folders need to be copied/merged into the Skyrim data folder (not inside of another folder). Thanks and shine on.

**Comment by DarkenTheSun807** [comment]
`Skyrim Data folder location in the nemesis.ini file was wrong`
This was my problem. My skyrim install is in a strange place, so fixing this put everything right.

**Comment by RichDavis1** [comment]
> At the risk of necro'ing a dead thread I had this issue and resolved it. I went back to my Skyrim SE LO and updated it and went to rerun Nemesis. When I updated the Engine it would crash at 2%. Poking around in my Nemesis_Engine directory I noticed that the Skyrim Data folder location in the nemesis.ini file was wrong. Once I put in the correct location it worked (Through MO2) with no issues! Hope this helps someone.

You helped me! I have to keep adding my se filepath to nemesis.ini everytime I open MO2.

**Comment by haraldwulf** [comment]
> 
> 
> At the risk of necro'ing a dead thread I had this issue and resolved it. I went back to my Skyrim SE LO and updated it and went to rerun Nemesis. When I updated the Engine it would crash at 2%. Poking around in my Nemesis_Engine directory I noticed that the Skyrim Data folder location in the nemesis.ini file was wrong. Once I put in the correct location it worked (Through MO2) with no issues! Hope this helps someone.

I'm using a wabbajack mod pack via MO2.  In "nemesis.ini" was written the actual Skyrim/Data location instead of the "X:\The Phoenix Flavour\Stock Game\Data". Thanks for pointing to the solution!

**Comment by danielabendroth** [comment]
> > At the risk of necro'ing a dead thread I had this issue and resolved it. I went back to my Skyrim SE LO and updated it and went to rerun Nemesis. When I updated the Engine it would crash at 2%. Poking around in my Nemesis_Engine directory I noticed that the Skyrim Data folder location in the nemesis.ini file was wrong. Once I put in the correct location it worked (Through MO2) with no issues! Hope this helps someone.
> 
> I'm using a wabbajack mod pack via MO2. In "nemesis.ini" was written the actual Skyrim/Data location instead of the "X:\The Phoenix Flavour\Stock Game\Data". Thanks for pointing to the solution!

Thank you for saying that! I'm having the same issue with the same mod pack and your comment solved it for me!

**Comment by stain2003** [comment]
> At the risk of necro'ing a dead thread I had this issue and resolved it. I went back to my Skyrim SE LO and updated it and went to rerun Nemesis. When I updated the Engine it would crash at 2%. Poking around in my Nemesis_Engine directory I noticed that the Skyrim Data folder location in the nemesis.ini file was wrong. Once I put in the correct location it worked (Through MO2) with no issues! Hope this helps someone.

It helped!! I changed my game directory but somehow the same day it still work fine.

**Comment by tyrell-wallace** [comment]
All I had to do was set the correct data folder on the .ini file and move all 4 files, including meta.ini to the Skyrim Data folder
