### ISSUE TITLE
[Request] Nemesis source scripts have the wrong path

### ISSUE THREAD

**Issue by Qudix** [ShikyoKira/Project-New-Reign---Nemesis-Main#200]
The correct path should be Data/Scripts/Source and not Data/Source/Scripts. Bethesda packaged the CK scripts incorrectly and never fixed it. A few authors have taken this to mean that it was intentional. As you have probably seen, the vast majority of mods are using the correct path (including SKSE).

**Comment by ShikyoKira** [comment]
I assume you are talking about SSE. But I don't think so. I just tried putting all the sources into `Data/Scripts/Source` and go to CK and check if I can open the file there nope, it doesn't work
![image](https://user-images.githubusercontent.com/31563634/79064584-b33d2680-7cdc-11ea-85c0-7e30e07e1ef3.png)

![image](https://user-images.githubusercontent.com/31563634/79064608-ee3f5a00-7cdc-11ea-98b0-8bf1b32f15c4.png)
as you can see the selections in the box got grey out

after i move them back to `Data/Source/Scripts`
![image](https://user-images.githubusercontent.com/31563634/79064654-45ddc580-7cdd-11ea-831a-2a5c921755f9.png)

![image](https://user-images.githubusercontent.com/31563634/79064689-9ce39a80-7cdd-11ea-82f9-969ef4567c0d.png)
I can compile them in CK again. So I don't think it is a mistake while i do think it is a stupid thing for them to change

**Comment by Qudix** [comment]
That's because the path in CreationKit.ini is set incorrectly
![image](https://user-images.githubusercontent.com/17361645/79080353-c3073b80-7cd9-11ea-8c4b-ac88503a2276.png)

**Comment by ShikyoKira** [comment]
hmm... mine is in default tho. Unless you mean to tell me the default is wrong as well, not just the packaging

Reverting it back to the same path as LE would essentially remove the necessity of separating LE and SE. My concern is how do one know it is wrong tho? What makes LE path right?

**Comment by Qudix** [comment]
From what I remember a bethesda employee confirmed it on the Bethesda.net forums. Of course I can't find it anymore because every link we had from back then just redirects to the main page now and trying to do indirect searching of similar terms on google brings up no results. It also helps that SSE is literally the only one like this. Even Fallout 4 has it's scripts packaged as Scripts/Source/[User, DLC, etc]

**Comment by ShikyoKira** [comment]
hmm.. so far there isn't any notable issue with it being in a "wrong" path. But since it can help eliminate the need to separate both SE and LE for nemesis and we have mods to prove that the "right" path has no issue, it is nonetheless a good thing. Less hassle and less work
