### ISSUE TITLE
Update Behavior Engine reaching 44%, then closing

### ISSUE THREAD

**Issue by mookachalupa** [ShikyoKira/Project-New-Reign---Nemesis-Main#202]
Selecting AGO and CGO+.

**Comment by ShikyoKira** [comment]
selecting AGO and CGO+ doesn't matter during engine update. It only matters during the patch when you launch the engine

**Comment by mookachalupa** [comment]
Ah well, unselecting all and letting the engine update reaches either 43% or 71% both, and proceeds to close without error code. The first time I installed nemesis this problem didn't exist, but now it does for some reason

**Comment by giddles** [comment]
I might have found a solution? I moved where my Skyrim Special Edition folder was located recently. I went through the "nemesis.ini" file and changed the path to be suitable under "SkyrimDataDirectory". This seems to have fixed my Engine Update close without error, at least.

**Comment by mookachalupa** [comment]
Editing the data directory in the ini doesn't seem to impact its crashing. Don't know if I should have to move the location of my game on my HDD just for Nemesis to work also xD I just want my animation mods to work together

**Comment by ShikyoKira** [comment]
it closing without any message is quite a suspicious behavior

**Comment by ShikyoKira** [comment]
anyway, this is a Duplicate of #198 . The symptom is it crashes while only updating regardless of the percentage. It is likely on the threading part. I'll see if I make it to a managed thread as i do for my devs build, see if it works or not
