### ISSUE TITLE
Compatability with Random Idle Animation

### ISSUE THREAD

**Issue by BenAric91** [ShikyoKira/Project-New-Reign---Nemesis-Main#209]
Many have already brought it up on the page for that mod, but since you have detectors for Sexy Move and XPMSE, I was wondering if it was possible to do something similar with RIA.

**Comment by ShikyoKira** [comment]
Not possible without modifying the skse plugin. RIA uses skse bypassing normal rule. So I can't do anything about it. The best way to "solve" this is to create a whole new mod and it is fairly simple to do so, but i'm not sure why it need to use skse plugin to achieve something so simple
