### ISSUE TITLE
Adding new animations

### ISSUE THREAD

**Issue by BBakers** [ShikyoKira/Project-New-Reign---Nemesis-Main#213]
I'm not sure if this is a new issue or not but I'm confused on how to add animations to Nemesis. My characters and creatures just stand in the idol pose until the animation timer runs out or I hit my end hotkey.

**Comment by ShikyoKira** [comment]
is this an inquiry or issue?

**Comment by BBakers** [comment]
> is this an inquiry or issue?

Issue. The interphase will not register the animations

**Comment by ShikyoKira** [comment]
how did you do it? Are you a user or modder?

**Comment by BBakers** [comment]
A user. Also noticed that Nemesis has a hard time registering animations that use objects.

**Comment by ShikyoKira** [comment]
you got videos or pictures?

**Comment by ShikyoKira** [comment]
Closed. Because no update for this issue for more than a month and I don't even know what's the issue to begin with
