### ISSUE TITLE
Nemesis engine won't update, error (1190)

### ISSUE THREAD

**Issue by Sqrmellow** [ShikyoKira/Project-New-Reign---Nemesis-Main#214]
as the title states the engine won't update and wont run until its been updated.

https://imgur.com/ej97EI8

reinstalling nemesis hasn't helped.
I am running nemesis through MO but trying to run it outside of MO doesn't change anything.

**Comment by ShikyoKira** [comment]
does running with CGO fix it?

**Comment by Sqrmellow** [comment]
the Combat Gameplay Overhaul? or is that something else?
I already have the combat overhaul installed, I didn't think it could effect the Nemesis engine's ability to update

**Comment by Sqrmellow** [comment]
so I uninstalled the combat overhaul which caused Nemesis to start without any text, one computer restart later and it boots and updates just fine

**Comment by Sqrmellow** [comment]
I also disabled several other mods that I though might be a problem but sofar only the combat overhaul is the one effecting anything

**Comment by ShikyoKira** [comment]
ok, for that error, check if you have missing file for CGO. See if `data/nemesis_engine/mod/dscgo/0_master/#0863.txt` exists. If it can be found there, cross check the file with this text
`
		<hkobject name="#0863" class="hkbStateMachine" signature="0x816c1dcb">
			<hkparam name="variableBindingSet">#1254</hkparam>
			<hkparam name="userData">0</hkparam>
			<hkparam name="name">MRhLeftHandOverride</hkparam>
			<hkparam name="eventToSendWhenStateOrTransitionChanges">
				<hkobject>
					<hkparam name="id">-1</hkparam>
					<hkparam name="payload">null</hkparam>
				</hkobject>
			</hkparam>
			<hkparam name="startStateChooser">null</hkparam>
			<hkparam name="startStateId">0</hkparam>
			<hkparam name="returnToPreviousStateEventId">-1</hkparam>
			<hkparam name="randomTransitionEventId">-1</hkparam>
			<hkparam name="transitionToNextHigherStateEventId">-1</hkparam>
			<hkparam name="transitionToNextLowerStateEventId">-1</hkparam>
			<hkparam name="syncVariableIndex">-1</hkparam>
			<hkparam name="wrapAroundStateId">false</hkparam>
			<hkparam name="maxSimultaneousTransitions">32</hkparam>
			<hkparam name="startStateMode">START_STATE_MODE_DEFAULT</hkparam>
			<hkparam name="selfTransitionMode">SELF_TRANSITION_MODE_NO_TRANSITION</hkparam>
			<hkparam name="states" numelements="9">
				#1154
				#1153
				#1052
				#1051
				#1049
				#1048
				#1047
				#1046
				#0867

				#dscgo$205 #dscgo$98

			</hkparam>
			<hkparam name="wildcardTransitions">#0864</hkparam>
		</hkobject>
`

**Comment by Sqrmellow** [comment]
Thanks for getting back to me on this, I some how managed to get it to work with a couple re-installs, but just to be sure I went through the file you showed and it all looks to be in order now. Thanks again!
