### ISSUE TITLE
Lot of warning counts 

### ISSUE THREAD

**Issue by ImSamhel** [ShikyoKira/Project-New-Reign---Nemesis-Main#216]
I updated the engine with selecting the proper mods, it detected everything and supposedly completed the update without errors. But after i clicked on the warning check, it counted 6035 warnings, and with every single warning it containts the following line: _"The animation will not work"_
I don't know if i should be worried about this, but i'm worried about this. Will my animations still work as intended, and these are really just for mod authors? I'm using nemesis for the first time and that's why i'm curious.

**Comment by ShikyoKira** [comment]
is anything broken in your skyrim?

**Comment by ImSamhel** [comment]
I tried it and it seems totally normal to me. Every animation seems to work normally. But idk why it's warning me for these things then :/

**Comment by ShikyoKira** [comment]
then ignore it. As stated at the bottom of the log, these warning messages are for mod author not mod user

To other users who have see similar behavior, please only make report when something is broken. Often than not it is unrelated to this issue but do bring it up along with other observations not just this "symptom"

I'll begin blocking normal users from using this feature in future version
