### ISSUE TITLE
Nemesis won't open through MO2

### ISSUE THREAD

**Issue by hexiest** [ShikyoKira/Project-New-Reign---Nemesis-Main#218]
I've newly installed Nemesis through MO2, and can't get it to run as an executable through the mod organizer. 

_It will run outside of MO2, which is why I am making a new issue as I saw there was someone else with the same issue ( **#211** ) but they couldn't run it at all, not just through MO2._

I followed all the same troubleshooting steps as issue **#211** except for reinstalling MO2 as this doesn't seem like it would be related. I have also tried marking the _Nemesis Unlimited Behavior Engine.exe_ to always run as an administrator.

Any help with this would be great! I really want to try Nemesis but I am quite literally unable to.

**EDIT: I fixed this by deleting the file path in the "Start in" section for the executable... for some reason it was trying to start in the Skyrim SE Data folder... my mistake, please disregard.**

**Comment by ShikyoKira** [comment]
yes, i got another same issue and it is the start in issue. thanks for your update
