### ISSUE TITLE
ERROR(1008)

### ISSUE THREAD

**Issue by Creuserey** [ShikyoKira/Project-New-Reign---Nemesis-Main#225]
"Unable to locate Skyrim Data folder. This tool must be executed in skyrim's data folder"

What should I do?

**Comment by ShikyoKira** [comment]
install this tool like a mod through your mod manager

**Comment by ShikyoKira** [comment]
it has been a week without update. I'll close this issue as this is more like an inquiry than an issue

**Comment by unwiredzombie** [comment]
I have the same issue and installed via Vortex. I've insured that I'm initiating it from the Skyrim Special Edition Data folder. I also tried updating the ini file to have the path but it is detecting the path correctly: 
Detected Path: D:\Game Folder\steamapps\common\Skyrim Special Edition\Data
ERROR(1008): Unable to locate Skyrim Data folder. This tool must be executed in skyrim's data folder

Could it be an SSE problem?

**Comment by slicstar** [comment]
I had the same problem on skyrim legegendery addition all i did was this
Go to the skyrim file directory 
Find data
The find the nemesis folder 
Then  the configuration  setting folder
Just below the nemesis exe
Open it  see the list find the first 
Thing called skyrim data directory =defalt 
Change the default into the exact 
Direction of your skyrim data
