### ISSUE TITLE
Nemesis requires access to internet to run?

### ISSUE THREAD

**Issue by drac0s** [ShikyoKira/Project-New-Reign---Nemesis-Main#227]
I try to use Nemesis without internet, and wont load, needs internet to work?

**Comment by whitewolf2899** [comment]
Nope not needed

**Comment by ShikyoKira** [comment]
no where in the program requires internet connection. I suggest you look for the source of your issue in other places

**Comment by drac0s** [comment]
> en ninguna parte del programa requiere conexión a internet. Te sugiero que busques la fuente de tu problema en otros lugares

Nemesis doesn't work for me, I try to run it and it just tells me that it couldn't load, I don't know if it's because I don't have internet on the PC where I run it
Please help
