### ISSUE TITLE
Combat Gameplay Overhaul & Character Behavior Enhanced some underwater fixes needed

### ISSUE THREAD

**Issue by Nepr0** [ShikyoKira/Project-New-Reign---Nemesis-Main#230]
Underwater:
Wielding weapon in right hand and magic in left hand - magic in left hand doesn't work.
If you dual wield weapons both right and left hand work correctly.
Wielding spells in both hands works correctly. Magic shoots from both hands.
Bow attack don't work underwater at all.

**Comment by ShikyoKira** [comment]
does this happen without nemesis? rmb to reinstall both mods before you do a test without nemesis, due to the nature of MO2's virtual filesystem, there is still a possibility that nemesis will overwrite the behavior files in it

**Comment by Nepr0** [comment]
in what order should I load mods? 
![Untitled](https://user-images.githubusercontent.com/51249555/80211941-9d94fe80-8604-11ea-91fa-181eab05e728.jpg)
I don't think it will work because both CBE and CGO change the same thing. I would go alone with CGO but it doesn't enable underwater combat.

**Comment by Nepr0** [comment]
I tried without Nemesis and it is as I mentioned above when I let CBE win the file and esp load order conflict then there is no leaning and dodging, no mid air attacks, weapon switching and weapon anims specific to CGO, when I let CGO win then there is no underwater combat.

**Comment by ShikyoKira** [comment]
Based on what you said, unfortunately this isn't something i can do. This has to do with CGO's implementation is in conflict with or not fully compatible with CBE. It will be up to the author to manually create a patch or the author to change its implementation avoid conflict issue.

Nemesis only merges both implementations together but doesn't guarantee to solve all compatibility issues, so... this is out of Nemesis' capability

Truth to be told, I can manually create them, but "manual" is never the purpose of Nemesis I'm sure we all are aware of that. In the future, I will no longer support any kind of patches, it will be up to the mod author to do using all the tools I have developed for them

**Comment by Nepr0** [comment]
> Based on what you said, unfortunately this isn't something i can do. This has to do with CGO's implementation is in conflict with or not fully compatible with CBE. It will be up to the author to manually create a patch or the author to change its implementation avoid conflict issue.
> 
> Nemesis only merges both implementations together but doesn't guarantee to solve all compatibility issues, so... this is out of Nemesis' capability
> 
> Truth to be told, I can manually create them, but "manual" is never the purpose of Nemesis I'm sure we all are aware of that. In the future, I will no longer support any kind of patches, it will be up to the mod author to do using all the tools I have developed for them

If author of CGO makes underwater combat it will render Character Combat Behaviors obsolete. Unfortunately he doesn't have it on his to do list. :C
