### ISSUE TITLE
Incorrect version in log, v0.83c but shown v0.83b in log

### ISSUE THREAD

**Issue by bakonburger** [ShikyoKira/Project-New-Reign---Nemesis-Main#236]
After reading 0Dser animations (which i suppose is from CGO considering author name(?) it goes spastic about 64bit hkx animations.
This is with the (LE) 0.83b nemesis + (LE) pcea + FNIS creature pack (happens without it aswell) and (LE) Combat Gameplay Overhaul. This happened last time I tried aswell, and I also checked that I didn't run any SSE animations then, as I have done that error before.

I also checked CGO in the launcher as well as gender specific animations which I guess you should like with FNIS (Couldn't find any info on this, and your link was just 12345 which went to unrelated mod)

Sorry for dupe issue but the other ones didn't actually go anywhere. Added the logs (from the launcher) and patchlogs, added to their own file as I had it all in notepad++ keeping track of em.
Best regards,
Bakon
[Log and patchlog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4561916/Log.and.patchlog.txt)

Edit: Also saw that the logs i posted were from when i ran a slightly older version, but I tried again with the very newest LE version and everything is identical. Apparently 0DSer is there with or without CGO so I suppose its some sort of standard animations or something?

**Comment by ShikyoKira** [comment]
Did you get the right PCEA version? Its PCEA issue. Kindly report this to Nemesis PCEA on nexus. I'll keep this for the incorrect version issue in log

**Comment by bakonburger** [comment]
Fixed it by deleting all the animation files that were in the nemesis pcea install, for some reason there were incompatible animations with the mod or something along those lines.
