### ISSUE TITLE
Momo Acrobatic Jump and 360 Movement Behavior Conflict

### ISSUE THREAD

**Issue by KenLee123** [ShikyoKira/Project-New-Reign---Nemesis-Main#237]
Momo Acrobatic Jump SE (v1.0.1) and 360 Movement Behavior SE (v1.3.2) appear to conflict despite patches being enabled in Nemesis, causing Momo jumping animations to be overwritten / ignored.

From what I can tell, issue occurs from 360 Movement Behavior v1.3.0 onwards due to the implementation of 360 jumping.

**Comment by ShikyoKira** [comment]
Mod conflict is not mine to fix. It is the mod author's responsible, not tool's developer
