### ISSUE TITLE
Update engine super lag

### ISSUE THREAD

**Issue by IdaeroAce** [ShikyoKira/Project-New-Reign---Nemesis-Main#240]
This mostly only happen when I still open Nemesis folder. Sometimes still happen if I still open Skyrim folder.

So I need to close all of File Explorer windows before doing it. This super lag disable my touch pad, but mouse still work. It will work again after I put laptop to sleep or restart. Windows 10 1903. Maybe something to do with Windows Defender? o.o
I’ll try disable it next time, wont do it now because i’m afraid it will break skyrim again. Been 10 hours figuring out ctd because of Nemesis :p

**Comment by ShikyoKira** [comment]
u don't have to update engine every time, only when it tells you to
