### ISSUE TITLE
MT_jumpfall animation unregistered

### ISSUE THREAD

**Issue by ChineseBlin** [ShikyoKira/Project-New-Reign---Nemesis-Main#241]
title says it for author i guess...

for some reason the engine is not adding the fall and landing animations to the animation behavior list, causing this... goofy but not game breaking bug... where characters jump and skip directly to the idle/moving animation.

 here's the full log should it be necessary.

[nemesis error log .txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4567166/nemesis.error.log.txt)

EDIT; this is LE.

**Comment by ShikyoKira** [comment]
CGO issue not nemesis. Please always check the source of issue so that you don't bother the wrong person
