### ISSUE TITLE
Error 2022 During Update Engine

### ISSUE THREAD

**Issue by Aaronavich** [ShikyoKira/Project-New-Reign---Nemesis-Main#242]
Hi, I am using MO2 and Nemesis 0.83c and attempting to update with 'tk dodge' selected as per the mod guide I am using for sse and receiving this error code 2022.

Installing Nemesis directly into sse data folder allows the update to complete successfully.

**Comment by Aaronavich** [comment]
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4568048/UpdateLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4568049/UpdateLog.txt)

**Comment by jeffreySJ** [comment]
I am also getting this same issue

**Comment by ShikyoKira** [comment]
this matter has been dealt with in devs version. Thanks for reporting still
