### ISSUE TITLE
ERROR(2003) while trying to update the engine

### ISSUE THREAD

**Issue by Moltenhead** [ShikyoKira/Project-New-Reign---Nemesis-Main#243]
Hi and thanks for the work.
Just tried to update the engine and now get this : 

```
Initializing engine update

ERROR(2003): Invalid file name. File name must only be #<modcode>$<id> or #<id>. Please contact the mod author
File: mod\dscgo\_1stperson\magicbehavior\#dscgo$20.txt.vortex_backup

Failed to update engine
```

**Comment by Moltenhead** [comment]
Corrected reinstalling Nemesis.
The error seems to get caused buy Vortex which seems to create backups of files.

**Comment by Mookymilk** [comment]
> I tried reinstalling Nemesis multiple times and i keep getting this error no matter what i do.

Did anyone ever find a fix for this, I just installed The newest ABR 5.7.9 build and I'm getting this error code
