### ISSUE TITLE
I do not know what to do but mt game crashes everytime I load a save.

### ISSUE THREAD

**Issue by Emorm** [ShikyoKira/Project-New-Reign---Nemesis-Main#244]
Checking engine version
Engine is up to date
Version Code: 477-389

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: aarm
Mod Checked 3: agpo
Mod Checked 4: dscgo
Mod Checked 5: dsmove

Mod installed: Anubs Futa
Mod installed: Anubs Human
Mod installed: CriticalHit
Mod installed: FlowerGirlsSE
Mod installed: NAR
Mod installed: SexLab
Mod installed: SexLabAP
Mod installed: SexLabAroused
Mod installed: SexLabCreature
Mod installed: SexLabTDFAggressiveProstitution
Mod installed: XPMSE
Mod installed: ZaZAnimationPack
Mod installed: ZaZAnimationPack+

ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: C:\Users\Asus\AppData\Local\Nemesis\Nemesis_AA_Core.pex
Message: boost::filesystem::remove: Dosya ba�ka bir i�lem taraf�ndan kullan�ld���ndan bu i�lem dosyaya eri�emiyor: "C:\Users\Asus\AppData\Local\Nemesis\Nemesis_AA_Core.pex"

Failed to generate behavior

 I have been using Nemesis for nearly a month for a week my game crashes everytime I load game after running nemesis so I start a new game. Also my Nemesis never fully stop even it says %100 it doesn't allow me to close it even after 30 minutes so I close it with program manager.

**Comment by ShikyoKira** [comment]
what you have described are few issues together. Please submit 1 issue at a time. See if there is any duplicate issue. If there is, i'll close the current issue. Kindly edit your issue title to specify your issue

**Comment by ShikyoKira** [comment]
No update for this issue. And seemingly a duplicate issue of #195
