### ISSUE TITLE
Install OSA (and OSEX) using Nemesis

### ISSUE THREAD

**Issue by Riotmxker** [ShikyoKira/Project-New-Reign---Nemesis-Main#250]
Hi, I'm recently using this Nemesis Engine (and yes, it is great). So my problem is I don't know if I can use OSA and OSEX using Nemesis. If there's any way to use it please tell me, thanks

**Comment by ShikyoKira** [comment]
Use then ask later. I can't go around test every mod in the community. Sorry, it has to be done this way for I have to focus on the development not testing. Any form of inquiry kindly reach me directly either through discord (Shiki - ShikyoKira#3754) or reddit (u/shikyokira)
