### ISSUE TITLE
error (2022).

### ISSUE THREAD

**Issue by max6186** [ShikyoKira/Project-New-Reign---Nemesis-Main#252]
what is the problem?

[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4605116/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
Reinstall nemesis, you might have missing file. And this error will be obsolete start in v0.84 due to its ambiguity

**Comment by max6186** [comment]
it fixed.

thanks for the help.
