### ISSUE TITLE
Everyone T Posing

### ISSUE THREAD

**Issue by RaccKing21** [ShikyoKira/Project-New-Reign---Nemesis-Main#254]
I followed this tutorial: https://youtu.be/4lSp3tZI2xc
Installed CGO and everything according to instructions.
Disabled animation replacers just in case.

Warning Check says: animation has not been registered in _1stperson\firstperson.hkx file. The animation will not work. Please contact mod author.

All animations worked perfectly with FNIS
Please help

**Comment by ShikyoKira** [comment]
Duplicate of #220
