### ISSUE TITLE
Initializing engine update ERROR(1190): 

### ISSUE THREAD

**Issue by gnomad1618** [ShikyoKira/Project-New-Reign---Nemesis-Main#258]
Initializing engine update

ERROR(1190): Missing state machine info node detected. Please contact the mod author
Mod: zcbe
ID: #1995
State Machine Info Node: #zcbe$82

Failed to update engine.

I am attempting to install Nemesis with the Ultimate Skyrim mod package.
I do not have Zartar's Character Behaviors Enhanced installed - assuming that's what zcbe is referring to

**Comment by ShikyoKira** [comment]
I don't know what Ultimate Skyrim mod package included, this isn't my problem. Sorry you have to deal with this. Try contact the Ultimate Skyrim's author. Before you do that, make sure you do your due diligence before reporting to him. Thoroughly test the issue, testing should be done by users before bothering anyone about it
