### ISSUE TITLE
TUDM - crosshair vanishing, animation stuck after transformations, double stamina use

### ISSUE THREAD

**Issue by h-joerg** [ShikyoKira/Project-New-Reign---Nemesis-Main#260]
First of all - I got the link to TUDM off a reanimation project, so if it's outdated, please ignore this. Here's the download link: https://drive.google.com/open?id=0B2VgBVA9jE6RTjJiYnRTTE9qRUE
I've been experiencing three issues. All of them happened while using Nemesis, though they may not be related.
1) Whenever I leave sneak mode, my crosshair disappears. I assume this has something to do with how the mod/Skyrim handles the crosshair upon leaving sneak. Upon pressing the sneak button designated  for actually dodging, it reappears. Any way to fix this? This is on a new save only running TUDM and the required masters/SKSE.
2) After transforming back from a VL/werewolf state, the first dodge will get stuck mid-animation. This can be fixed by pressing the change animation style button once, but has to be done every time you transform back into human form
3) In first person, dodges will consume both roll and sidestep stamina. Temporary fix: just remove stamina cost from one of them and only use one type of dodge.

Sorry if this is the wrong place to ask this but unfortunately your mod disappeared off the face of the Earth and since it is kinda Nemesis-related, I hoped you could help.

**Comment by ShikyoKira** [comment]
Not Nemesis, something out of nemesis scope. I will take note but close this issue. Thanks for reporting still
