### ISSUE TITLE
CTD from Kill Moves

### ISSUE THREAD

**Issue by Hykilla** [ShikyoKira/Project-New-Reign---Nemesis-Main#261]
I get a CTD in Markarth after the Intro stab animation as soon as that guy Weylin stabs Margret my game CTDs when he plays the Kill Move animation "pa_1HMKillMoveBackStab".
I've tried to Remove Nemesis and the CTD from Kill Moves does not occur anymore and after a further investigation i discovered is that sometimes the mod "VioLens" a mod that basically plays Kill Moves. When playing Certain Kill Move Animations the moment before a Kill Move is about to occur the game instantly CTDs, the ones i found so far that CTD's my game are: "pa_1HMKillMoveBackStab" , "1HMKillMoveJumpStab00" , "1HMKillMoveGrabStabShort00", almost everything else plays properly.
I've tried to remove every mod that would edit combat or kill moves including VioLens as well and the CTD still occurs on Nemesis.

**Comment by ez009** [comment]
Are you using TUDM - Violens Patch.esp ?   if not you can get it here:
 https://www.nexusmods.com/skyrimspecialedition/mods/33049?tab=description
 in the description - middle of page.

**Comment by Hykilla** [comment]
> 
> 
> Are you using TUDM - Violens Patch.esp ? if not you can get it here:
> https://www.nexusmods.com/skyrimspecialedition/mods/33049?tab=description
> in the description - middle of page.

I am not using TUDM, I am using the Dodge from Combat Gameplay Overhaul from DServant which is the only combat mod i am using, Would that be relevant for CGO as well?

**Comment by ShikyoKira** [comment]
can you remove animation and behavior related mods like CGO, and then go through the same process to test if its break. If when nothing else present but Nemesis, then it is certainly Nemesis' fault. If it only CTD when certain mod or mods are present then we have to investigate into it. Update me after you on your findings on that

**Comment by Hykilla** [comment]
> 
> 
> can you remove animation and behavior related mods like CGO, and then go through the same process to test if its break. If when nothing else present but Nemesis, then it is certainly Nemesis' fault. If it only CTD when certain mod or mods are present then we have to investigate into it. Update me after you on your findings on that

I believe i figured out what causes the CTDs on my end. So i started by removing all my animation and behavior mods entirely and the kill moves no longer CTDs my game, then i added back all my mods one by one and repeating the same testing process of kill moves. after i've installed all my animation mods back without any CTD i've noticed that after as soon as i pass the 10k animations the CTDs from Kill Moves started happening again.

**Comment by ShikyoKira** [comment]
thanks for the crucial information. Is the CTD triggered by the killmove or the location?

**Comment by Hykilla** [comment]
> 
> 
> thanks for the crucial information. Is the CTD triggered by the killmove or the location?

From my tests it's mostly triggered by the Kill Move Animation itself, I've been experimenting with VioLens fighting a lot of enemies at once in different locations and most of the Kill Moves would work perfectly, but some would crash the game even before you get to see them playing. In Markarth its always a 100% CTD since Weylin always plays the same Kill Move animation.

**Comment by ShikyoKira** [comment]
This issue might be related to #178

**Comment by Hykilla** [comment]
Hello, i wanted to say that i've tried the latest Nemesis update and my Kill Move CTD issue still persists. I've tried everything and been experimenting a lot with it since the update was released and the conclusion is the same, if i go above 10k animations i would get CTD from the same Kill Move animations, Markarth being still the 100% CTD location
