### ISSUE TITLE
PC Overload and Freezing while updating

### ISSUE THREAD

**Issue by silentteddy** [ShikyoKira/Project-New-Reign---Nemesis-Main#265]
Sorry for my English is not verygood. I have an issue that while I click on updating my pc start lag and overload then it's turn to the point of nearly freezing. I try many methods even uninstall FNIS but the same problem still occurred.
I use latested version for Legendary Edition.

**Comment by ShikyoKira** [comment]
Duplicate of #240 
Issue has been addressed. Thanks for reporting
