### ISSUE TITLE
XPMSSE Styles page is blank

### ISSUE THREAD

**Issue by SirArlen** [ShikyoKira/Project-New-Reign---Nemesis-Main#267]
I have Nemesis PCEA, AGO, CGO, Animated Armoury, 360 Movement Behaviour and Ultimate Combat installed. In one of my older save before transferring to Nemesis, i have FNIS installed and the XPMSE styles tab works fine, even after transferring to Nemesis. Recently i made a new character but the Styles tab is just blank with nothing inside, everything else are working as intended. I just want to use the belt-fastened feature

**Comment by ShikyoKira** [comment]
tick the FNIS.esp plugin that Nemesis has generated

**Comment by SirArlen** [comment]
> tick the FNIS.esp plugin that Nemesis has generated

i did, the FNIS.esp dummy for XPMSSE was activated in my load order when this was posted

**Comment by DroidZed** [comment]
Same happens to me : XPM32 SE + CGO + AGO + 360 MB + FNIS.esp (from FNIS itself) and no styles :/

**Comment by ShikyoKira** [comment]
Show us your screenshot of the XPMSE main page. It will show us which requirements you fail to meet

**Comment by SirArlen** [comment]
https://postimg.cc/c655yBfj
Strange, why didnt it detect the xpmse skeleton
