### ISSUE TITLE
Error 1190

### ISSUE THREAD

**Issue by RayzerCalitri** [ShikyoKira/Project-New-Reign---Nemesis-Main#268]
Hi,

I was testing Nemesis for the first time, and the first time I used it, it worked fine, but then If I click Update Engine, this shows up:
![nemesis_error](https://user-images.githubusercontent.com/65947635/82880529-db0be500-9f3e-11ea-8d80-16ef6164efd5.PNG)

**Comment by ShikyoKira** [comment]
Inform mod author not Nemesis' author. Thank you
