### ISSUE TITLE
Character Behaviors Enhanced patch doesn't work, character's T-posing on new save

### ISSUE THREAD

**Issue by actualsaltyduck** [ShikyoKira/Project-New-Reign---Nemesis-Main#269]
I tried this on my current save in SE and the characters t-posed, I tried it on another save with no other mods other than nemesis and character behavior enhanced and characters were still t-posing.

**Comment by ShikyoKira** [comment]
You have missing file(s). Start from v0.84, you will receive error if you have missing behavior file(s). I won't be held responsible for that

**Comment by actualsaltyduck** [comment]
So I just need to download the latest version, install it and then the problem will be fixed?

**Comment by ShikyoKira** [comment]
Installed latest version of Nemesis and CBE

**Comment by actualsaltyduck** [comment]
Ok this is kinda weird but this is how I've gotten it to work, instead of using the SE version of CBE, I downloaded the LE version and ported it through Cathedral Assets Optimizer and then used it with nemesis, then it finally started working, apparently the SE version is missing some files that is required by the patch in nemesis.

**Comment by ShikyoKira** [comment]
perhaps. Glad you got it to work. And yes, the CBE you downloaded from SE are incomplete or modified and not the original CBE from LE. You should inform the mod author
