### ISSUE TITLE
Nemesis animation count is higher than Fnis??

### ISSUE THREAD

**Issue by SH3R4TA5** [ShikyoKira/Project-New-Reign---Nemesis-Main#270]
I'm Trying the new nemesis (a great work tbh) but i noticed that it detect more animations from mods on my list, making almost double the amount i previously did with Fnis (which make CTD due animations limits... btw what is the number?) why is detecting so many? how it is considering animations to handle? and why Fnis give me a REALLY stable game without touching his own limit if Nemesis have a greater limit?

**Comment by ShikyoKira** [comment]
Yes, nemesis count animation from female and male independently. The reason being some females are female specific, hence only counted as 1. If female and male, then it will be counted as 2. Please read the readme on the main page as this is an example of issue that doesn't fit the criteria there

**Comment by SH3R4TA5** [comment]
I'm organizing my mod list once more, and maybe i'm going to need to make it again from the ground to make is as stable as before, but as far as things go, it si amazing; a 259 mod count and many of the Gameplay-wise features are working like a charm.

I cant thank you enough for the help and the effort put in this tool wish you luck with the future of this and other projects you have.
