### ISSUE TITLE
FNIS Horses Renewal is broken

### ISSUE THREAD

**Issue by Bloxxk** [ShikyoKira/Project-New-Reign---Nemesis-Main#271]
Cannot change the weapon sheathe styles. Says it cannot detect FNIS. When launching Nemesis I do get the "Running script: XPMSE detector .py" but it XP32 styles still do not show up. 

Also another issue which may be related to the FNIS thing is Horses Renewal "https://www.nexusmods.com/skyrimspecialedition/mods/18605?tab=posts"
does not work, the horses are all glitched out and broken.

Thanks.

**Comment by ShikyoKira** [comment]
Please only post 1 issue at a time. For XPMSE issue check this #267 
I'll look into the horse issue. But please screenshot your issue if possible

**Comment by ShikyoKira** [comment]
Please clarify this. Does removing Nemesis fixes the Horses Renewal bug that you have?

**Comment by Bloxxk** [comment]
Yes, removing Nemesis fixes the issue. I tested it with FNIS instead, and Horses Renewal seems to work fine. 
Here is a screenshot of the issue. The horses function but animation and meshes are broken.
![Skyrim Special Edition 5_27_2020 3_29_36 PM](https://user-images.githubusercontent.com/65991022/83064148-5baa0e80-a02f-11ea-981d-43a92d39a776.png)
![Skyrim Special Edition 5_27_2020 3_29_12 PM](https://user-images.githubusercontent.com/65991022/83064157-5e0c6880-a02f-11ea-8c98-fa7914f00a23.png)

**Comment by ShikyoKira** [comment]
I have 1 tester tried it and it works fine for him. I'll need more people to look into this. In the mean time, try removing all mods except Nemesis and Horse Renewal. I want to rule out the possibility of mod conflict

**Comment by ShikyoKira** [comment]
Thanks for your clarification. I haven't really been modding skyrim but developing Nemesis since i started this project. I only switch on my skyrim to test stuffs such as mod conflict, issue diagnosis and so on. So I'm not the best person to ask for this anymore unless it is Nemesis related

Anyway, I'll close this issue as it is not Nemesis' issue. Thanks again
