### ISSUE TITLE
3rd person character model freezing

### ISSUE THREAD

**Issue by BlackAzrael128** [ShikyoKira/Project-New-Reign---Nemesis-Main#272]
I'm not entirely sure if it's Nemesis Engine causing this but I'm having this weird issue where the character model in 3rd person will not move but I am still able to move the camera and attack.

It seems to be happening when I use the swords on back XP32 skeleton and swapping between 1st and 3rd person while sheating/unsheating a weapon. When it happens, if I go back to 1st person, I can still do everything perfectly fine though. But if I try to equip something else, the game crashes to desktop (haven't tried equipping something in 1st person during this bug though).

I am using the following mods which could be causing something like this:
- Combat Gameplay Overhaul
- Archery Gameplay Overhaul
- Ultimate Combat
- TK Dodge
- 360 Movement Behavior

Thanks in advance!

**Comment by ShikyoKira** [comment]
Please read the readme in the main page. I would appreciate if you can test more and post a video of it

**Comment by BlackAzrael128** [comment]
I made a few screenshots here, pardon the clutter, I haven't configured mods: https://imgur.com/a/AuWVSvV

**Comment by BlackAzrael128** [comment]
Nevermind, I think I found the issue. It was Ultimate Combat's "swing effect" option causing this.
