### ISSUE TITLE
Crashing during engine update (Works fine with 0.83)

### ISSUE THREAD

**Issue by DenenC** [ShikyoKira/Project-New-Reign---Nemesis-Main#274]
So I've completely removed the previous version and installed this new version and but now if I try to update the engine Nemesis crashes at around 94% with the "Nemesis Unlimited Behaviour Engine.exe has stopped working" message.

I've looked at similar instances of this happening in the previous version but none of the fixes have worked for me. When I remove 0.84 and reinstall 0.83 updating the engine works fine.

[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4694689/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
remove the generated files generated by v0.83

**Comment by DenenC** [comment]
> 
> 
> remove the generated files generated by v0.83
> 
> as reported by this user
> ![image](https://user-images.githubusercontent.com/31563634/83127822-32f84680-a10d-11ea-8966-267e529afe03.png)

I checked the overwrite folder and there aren't any files belonging to nemesis in there. I have it set up so everything nemesis generates gets written to a separate "Nemesis Output" folder.

I also deleted everything from this folder so Nemesis could write new files to it but the problem still persists.

Is there any other location that nemesis writes files to that I might've forgotten to remove?

**Comment by ShikyoKira** [comment]
Hmm... start by reducing mods then to find out the culprit. External programs can still affect files in other mods despite the virtual filesystem that MO2 offers

I'm not exactly sure which file could cause it to crash. But i would definitely like to know. Update me your findings

**Comment by DenenC** [comment]
> 
> 
> Hmm... start by reducing mods then to find out the culprit. External programs can still affect files in other mods despite the virtual filesystem that MO2 offers
> 
> I'm not exactly sure which file could cause it to crash. But i would definitely like to know. Update me your findings

Disabled all mods and plugins and the same thing happens. Also tried changing it so it writes straight to the overwrite folder and still no luck. Tried running Update engine outside of MO directly from the Skyrim data folder and it does update.

**Comment by ShikyoKira** [comment]
awesome. I was just about to ask you to run it outside of MO
Anyway, it seems to have nothing to do with mods but interaction with MO2. Is your MO2 the latest version?

Make sure these 2 folders are emptied when you try test running it. `data/meshes` and `data/nemesis_engine/temp_behaviors`

**Comment by DenenC** [comment]
> 
> 
> awesome. I was just about to ask you to run it outside of MO
> Anyway, it seems to have nothing to do with mods but interaction with MO2. Is your MO2 the latest version?
> 
> Make sure these 2 folders are emptied when you try test running it. `data/meshes` and `data/nemesis_engine/temp_behaviors`

**Updating MO to the latest version solved it** -  but now I'm having a problem where the engine is crashes at random points in the middle of updating animations (0.83 still updates animations without issues.)

**Comment by ShikyoKira** [comment]
since you said random, do you ever get to update it without any issue at least once from time to time, or every time you update, surely there will be a crash but at random points?

if it is at random points with a guarantee failure all the time, send me 3 instances of your updatelog.txt after running update 3 times. I would like to examine the pattern for these 3

**Comment by DenenC** [comment]
If I keep trying to run Nemesis eventually it succeeds at updating animations after failing over and over.

When I do it with nothing installed except Nemesis it works 100% of the time, and adding more animation mods seems to reduce the chance of it successfully running. The crash always happens as the animation bar stars filling.
