### ISSUE TITLE
Engine Update Problem

### ISSUE THREAD

**Issue by Shlaga** [ShikyoKira/Project-New-Reign---Nemesis-Main#280]
I installed using MO2 and every time when I run it and hit the "update engine" button, the bar gets all the way to 65% and gives me this error:

Initializing engine update

ERROR(2003): Invalid file name. File name must only be #<modcode>$<id> or #<id>. Please contact the mod author
File: mod\dscgo\_1stperson\1hm_behavior\#dscgo$138.txt.meta

Failed to update engine

I am 100% sure I installed it correctly but at this point I don't know what's causing this issue and I am out of ideas.

**Comment by Shlaga** [comment]
Nevermind I'm just really stupid, reinstalling the CGO mod fixed my issue.

**Comment by AvatarAsterix** [comment]
I have the same problem and I cant seem to get it to work even after reinstalling CGO and Nemesis itself.

**Comment by AvatarAsterix** [comment]
> I have the same problem and I cant seem to get it to work even after reinstalling CGO and Nemesis itself.

installed manually as stated in another issue, seems to work for now
