### ISSUE TITLE
error 1166

### ISSUE THREAD

**Issue by mynameisjeff420** [ShikyoKira/Project-New-Reign---Nemesis-Main#282]
when I try launching it, it freezes and I cant exit out of it

**Comment by ShikyoKira** [comment]
This issue does not mean the criteria shown in the description of the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repository. Issue will be closed if no update on this issue to meet its criteria within 5 days time

**Comment by mynameisjeff420** [comment]
I figured it out I didn’t have the latest version of nemesis and I also had to dodge installed but not enabled once I uninstalled it everything worked fine
