### ISSUE TITLE
Progress bar not filling?

### ISSUE THREAD

**Issue by OrganisedAnarchy** [ShikyoKira/Project-New-Reign---Nemesis-Main#284]
The progress bar won't fill even though the mod reports that generation is complete,
![image](https://user-images.githubusercontent.com/66269469/83434774-ff7e2a80-a432-11ea-908f-77fd6a5f8cef.png)

p.s. Sorry if already been posted couldn't be arsed checking.

**Comment by ShikyoKira** [comment]
I'm not sure if I am blind or what. But... do you have any issue in the first place?

**Comment by OrganisedAnarchy** [comment]
The animation bar not filling to full is normal?

**Comment by AuraOfPrimalMajesty** [comment]
> The animation bar not filling to full is normal?

It's not an issue, the bar represents how many animations you have installed. Hover your mouse over it.
