### ISSUE TITLE
Error 1210: Nemesis is telling me that behavior files are missing that none of my mods touch

### ISSUE THREAD

**Issue by BetaFalcon13** [ShikyoKira/Project-New-Reign---Nemesis-Main#285]
So I'm getting an error that says "ERROR(1210): Vital behavior file cannot be found. This will cause T-pose in game. To fix this, either reinstall the mod or manually restore this behavior file
File: c:\program files (x86)\steam\steamapps\common\skyrim special edition\data\meshes\actors\character\behaviors\swimidlebehavior.hkx"

I have looked through every single mod I have installed and not one of them contains this behavior file, so I checked the file previews for all of the ones that affect behaviors and as far as I can tell none of my mods are supposed to contain this file. Does Nemesis somehow delete files from the game's archives? Because the only instance of swimidlebehavior.hkx that I could possibly have is the vanilla one

**Comment by LaFlame6** [comment]
I am having the same issue; however, my behavior file is: jumpbehavior.hkx 
My error reads exactly the same though, just that different behavior error.

**Comment by ShikyoKira** [comment]
Because you guys are trying to install CBE on SSE that you got from Nexus. And that so called "CBE" in SE section of Nexus has missing files. Go download and convert the CBE from the LE section using CAO

This mod from SE nexus is giving me nothing but trouble. I'm not mad at you guys, but the uploader (Oracus0), not Zartar the creator

**Comment by BetaFalcon13** [comment]
I actually do not have either version of that mod installed, I looked into it, but decided it was too old and would cause too many issues, so I never even downloaded it

**Comment by ShikyoKira** [comment]
post the log shown in Nemesis when you launch the patch

**Comment by BetaFalcon13** [comment]
I would love to, but I have since reverted to an earlier set of behavior files generated by Nemesis, and I am now unable to recreate the issue

**Comment by ShikyoKira** [comment]
wait, does updating the engine and then generate the behavior files give you the same error again?

**Comment by BetaFalcon13** [comment]
It does not, I am unable to recreate the issue. Not sure what the problem was, when trying to generate new behavior files I completely uninstalled the previous ones, ran the engine exactly as I had before, and got the error, but then after reinstalling the old ones I was able to update them with no issue
