### ISSUE TITLE
Patch not showing up in nemesis even after engine updated

### ISSUE THREAD

**Issue by LaFlame6** [ShikyoKira/Project-New-Reign---Nemesis-Main#288]
Downloaded the latest version of nemesis last night and got the tool running through vortex. However, when I launch the tool and hit "update engine" a patch for AGO does not appear, though one for CGO does. When I "Launch Nemesis behavior engine" after selecting CGO, it says I have CGO and XPMSE like checked, though no word of AGO. How do I get AGO to appear and this also happened when I tried to use Animated Armory, a patch for nemesis was not in the section where I could check the box. 
My apologies if you're unable to help with this or I did something wrong. 
Thanks anyway!

**Comment by NielsGx** [comment]
AGO patch is on AGO mod page

**Comment by LaFlame6** [comment]
my apologies, I had not seen the patch in the AGO page, I just assumed one came prepackaged with the download of AGO itself. Thank you! sorry again

**Comment by ShikyoKira** [comment]
READ THE LOGGG WHEN YOU DOWNLOAD NEMESIS!!!!

It pisses me off when i spent about an hour gathering info and writing that but people can't even give a min reading that. Don't make me regret making this tool
