### ISSUE TITLE
Critical error warning, cannot update engine

### ISSUE THREAD

**Issue by pisichi** [ShikyoKira/Project-New-Reign---Nemesis-Main#291]
Initializing engine update

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: No mapping for the Unicode character exists in the target multi-byte code page.

Failed to update engine

If I tried to run it again it give me a empty critical error with a window pop-up and the program is not responding.

I tried switching to an older,newer version but the result is still the same.

**Comment by ShikyoKira** [comment]
This issue fails to meet the criteria stated in the description in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo. It will be closed if it still fail to meet the criteria after 5 day

**Comment by ShikyoKira** [comment]
5 days have passed without any update to meet the required criteria in order to fix this issue. This issue has been identified to be a duplicate of #273 , therefore it will be closed until further update on this matter to show that it is different from #273
