### ISSUE TITLE
Failed to output

### ISSUE THREAD

**Issue by alanktc** [ShikyoKira/Project-New-Reign---Nemesis-Main#292]
When I launch the engine I got thie error:

ERROR(1185): Failed to output D:\SteamLibrary\steamapps\common\Skyrim\data\scripts\Nemesis_AA_Core.pex

**Comment by ShikyoKira** [comment]
This issue fails to meet the criteria stated in the description in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo. It will be closed if it still fail to meet the criteria after 5 day

**Comment by Ode2Dstry** [comment]
So what was the fix for this?
