### ISSUE TITLE
nemesis crashing on launch

### ISSUE THREAD

**Issue by kodamant** [ShikyoKira/Project-New-Reign---Nemesis-Main#293]
so idk whats wrong with it, but i would rather not go back to fnis, heres the log file, previous versions worked fine, first problem ive had with this thing, but id like to get my buddy back to playing skyrim soon, as i cant exactly vouch for a stable game with nemesis doin, this.
[PatchLog - Copy.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4739233/PatchLog.-.Copy.txt)

**Comment by ShikyoKira** [comment]
Hi, this issue fails to meet the criteria of stated in the description in the main page of this issue. Check out recent issues regarding crash on launch
