### ISSUE TITLE
Error 6001/6002 [Solved]

### ISSUE THREAD

**Issue by Dakers-of-anvil** [ShikyoKira/Project-New-Reign---Nemesis-Main#294]
The thing is, i was updating my engine and this thing appeared
ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: There is no mapping on the target multi-byte code page for the Unicode character.
The same happens when launching engine

**Comment by Dakers-of-anvil** [comment]
I also tried everything it was mentioned in #195 but it didn't work

**Comment by ShikyoKira** [comment]
This issue fails to meet the criteria in the description in main page of this repo. It will be closed it still doesn't meet its criteria 5 days after posting

**Comment by Dakers-of-anvil** [comment]
After some testing i've tried the following (None of them worked)
1- Reinstall Nemesis
2- Force load libraries (I selected every single dll in nemesis folder)
3- Install older versions
I think i reached a point in where i don't know what could be the problem.

I've been reading other issues that mentioned ZaZ animation pack may be the cause of this error, i disabled the mod and it didn't work, the issue still persisted

I'll be informing if i have any succes on solving this issue

**Comment by Dakers-of-anvil** [comment]
Success!! It seems i may have found the problem , i disabled every single mod and the engine didn't give me any trouble.
I'll be posting wich mod is the cause of this issue soon

**Comment by Dakers-of-anvil** [comment]
TOTAL SUCCESS!!!! If you're using Zaz animation pack, disable it and install version 7.0 instead.
I hope this could be of help to anyone

**Comment by XxrivenxX** [comment]
Thanks brother you're the LEGEND new zaz  animations are messing things ZAZ ver 7 is safe 🫡
