### ISSUE TITLE
nemesis error

### ISSUE THREAD

**Issue by kodamant** [ShikyoKira/Project-New-Reign---Nemesis-Main#295]
so nemesis was crashing, didnt before, so i downgraded, got this at around half way through the engine update ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: invalid string position, so i though it could be some of the new animation mods im using, nope, same message but at around 70-80% 
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4741168/UpdateLog.txt)
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4741169/PatchLog.txt)
any ideas?

**Comment by ShikyoKira** [comment]
This issue fails to meet the criteria in the description in main page of this repo. It will be closed it still doesn't meet its criteria 5 days after posting

**Comment by kodamant** [comment]
i dont suppose you could link that cause i cant find it

**Comment by ShikyoKira** [comment]
https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main

**Comment by kodamant** [comment]
oh thanks! thats my bad, i didnt scroll down that far, sorry for puttin this up, turns out im just stupid and it was right there, again, so sorry, your doing a great job
