### ISSUE TITLE
Error 6001

### ISSUE THREAD

**Issue by Fallland9** [ShikyoKira/Project-New-Reign---Nemesis-Main#297]
Trying to update the engine just got it downloaded and this comes up: ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: �ڶ��ֽڵ�Ŀ������ҳ�У�û�д� Unicode �ַ�����ӳ�䵽���ַ���

**Comment by Fallland9** [comment]
The full thing is like this: Initializing engine update

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: �ڶ��ֽڵ�Ŀ������ҳ�У�û�д� Unicode �ַ�����ӳ�䵽���ַ���

Failed to update engine


btw im not nativ english speaker so sorry if im wrong with some words

**Comment by ShikyoKira** [comment]
Duplicate of #273
