### ISSUE TITLE
ERROR(2006) missing behavior file

### ISSUE THREAD

**Issue by lucasarts720** [ShikyoKira/Project-New-Reign---Nemesis-Main#298]
Hi everyone, im new to Nemesis, but watched a tutorial on how to install it...
im getting this every time im trying to update the engine, not sure about causes it. its a fresh install

[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4752860/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
if you are new, don't install a beta tool in your system. I don't recommend anyone new doing this as I am not liable nor I will help fix broken game. Error does not mean my tool has issue, start by looking at your side before reporting it to me

This issue fails to meet the criteria stated in the description in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo. It will be closed if it still fail to meet the criteria after 5 day

**Comment by ShikyoKira** [comment]
5 days have passed without an update to meet its requirement. Closed
