### ISSUE TITLE
Error 1190

### ISSUE THREAD

**Issue by dragonman1** [ShikyoKira/Project-New-Reign---Nemesis-Main#300]
ERROR(1190): Missing state machine info node detected. Please contact the mod author
Mod: dscgo
ID: #4510
State Machine Info Node: #dscgo$727
help

**Comment by ShikyoKira** [comment]
this is not a support ticket. This issue fails to meet the criteria stated in the description in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo. It will be closed if it still fail to meet the criteria after 5 day

**Comment by ShikyoKira** [comment]
Lack of necessary info and testing result by reporter. Closed
