### ISSUE TITLE
Error code 6001

### ISSUE THREAD

**Issue by ligitembo** [ShikyoKira/Project-New-Reign---Nemesis-Main#302]
so, i was looking around for some mods i could install. i came across tudm and i thought it would be a good idea to install it, because the dodge function from cgo didnt worked correctly. I saw that theres a new version for Nemesis (0.84 beta). i wanted to update it, i just simply overwrote everything and after that nothing worked anymore. i dont know what i should do, neither how to uninstall nemesis properly. tbh i cant imagine a skyrim without cgo/ago/nemesis and im not sure if i want to play with fnis again. id be really happy if i could get help. btw i tried to downgrade  it to 0.83c but it didnt worked either. (again i simply overwrite it.) thanks for your attention.

**Comment by ligitembo** [comment]
i forgot to mention that i got the error code 6001. i know theres a existing issue but it didnt help me.

**Comment by ShikyoKira** [comment]
![image](https://user-images.githubusercontent.com/31563634/84602293-d476ea80-aeb8-11ea-8a24-f32165e36c8e.png)

this issue fails to comply with following criteria and will be closed in 5 days. Error 6001 tells me little to none as this specific error code is general error not handled by Nemesis debug system
