### ISSUE TITLE
ERROR(2003)

### ISSUE THREAD

**Issue by M1xedNuts** [ShikyoKira/Project-New-Reign---Nemesis-Main#307]
ERROR(2003): Invalid file name. File name must only be #<modcode>$<id> or #<id>. Please contact the mod author
File: mod\zcbe\_1stperson\magicbehavior\#zcbe$39.txt.vortex_backup

Failed to update engine

-How can I fix this error?

**Comment by ShikyoKira** [comment]
install it manually. We are in discussion with vortex developers regarding support and how to go with it

If installing it manually fixes your issue, please close this issue. Thanks
