### ISSUE TITLE
enemies not attacking

### ISSUE THREAD

**Issue by HaloGalaxy25** [ShikyoKira/Project-New-Reign---Nemesis-Main#309]
So, I'm wondering if the bug regarding human enemies not attacking is fixed in the new version or is it still an ongoing issue?

**Comment by ShikyoKira** [comment]
This issue fails to meet the criteria stated in the description in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo. It will be closed if it still fail to meet the criteria after 5 days

**Comment by ShikyoKira** [comment]
5 days have passed without fulfilling the criteria. Closed
