### ISSUE TITLE
Reading error sometimes

### ISSUE THREAD

**Issue by yag1z** [ShikyoKira/Project-New-Reign---Nemesis-Main#312]
![2020-06-25](https://user-images.githubusercontent.com/21185100/85741802-65e12a80-b70b-11ea-92b6-833347351109.png)

It is happening sometimes not everytime. Then I close the Nemesis and run it again its goes back to normal state.

**Comment by ShikyoKira** [comment]
![image](https://user-images.githubusercontent.com/31563634/85765158-6fd54e80-b748-11ea-83cc-fe1871114bf1.png)

**Comment by ShikyoKira** [comment]
1 more thing, warning and error both words spelled differently. Please note that
