### ISSUE TITLE
Papyrus Spam with XPMSE weapons styles, details inside. The 8th line will *Shock* you

### ISSUE THREAD

**Issue by uncleseano** [ShikyoKira/Project-New-Reign---Nemesis-Main#315]
Heya Shikyo, another painful bug report for you

I'm getting a huge amount of Papyrus spam that starts pretty much once the game begins until I turn it off. You can see it below in the log I posted. It looks like this:
`[06/30/2020 - 09:16:00AM] Error:  (0001348A): cannot fetch variable named FNISaa_axeeqp of type int, returning 0.
stack:
	[ (0001348A)].WIDeadBodyCleanupScript.GetAnimationVariableInt() - "<native>" Line ?
	[Active effect 2 on  (0001348A)].XPMSEWeaponStyleScaleEffect.GetAnimVar() - "XPMSEWeaponStyleScaleEffect.psc" Line 1622
	[Active effect 2 on  (0001348A)].XPMSEWeaponStyleScaleEffect.SaveFNISData() - "XPMSEWeaponStyleScaleEffect.psc" Line 1628
	[Active effect 2 on  (0001348A)].XPMSEWeaponStyleScaleEffect.Restyle() - "XPMSEWeaponStyleScaleEffect.psc" Line 848
	[Active effect 2 on  (0001348A)].XPMSEWeaponStyleScaleEffect.onBeginState() - "XPMSEWeaponStyleScaleEffect.psc" Line 255
	[Active effect 2 on  (0001348A)].XPMSEWeaponStyleScaleEffect.GotoState() - "ActiveMagicEffect.psc" Line ?
	[Active effect 2 on  (0001348A)].XPMSEWeaponStyleScaleEffect.OnEffectStart() - "XPMSEWeaponStyleScaleEffect.psc" Line 222`

I reinstalled FNIS and the spam went away, redid Nemesis and it came back so I dunno. I mentioned it to Grovetama too but something isn't gelling between the two mods. It might not be a problem but I'm not a fan of seeing such papyrus spam! (and yes I only enable it for testing, not general play)

Tested out on a current save, and a new save without any mods. Thanks man. Best of luck with the bug squashing, gimmie a shout if you need any help

[Papyrus.2.log](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4850756/Papyrus.2.log)

**Comment by ShikyoKira** [comment]
Hi, fixing this will somewhat risk my tool violating someone's "rights". XPMSE hardcoded a script to get a specific variable that exists in FNIS but not in Nemesis as I don't use it. Despite the log being spammed, nothing significant enough to cause an issue. In accordance to the criteria stated in description in the main page of this repo. "Non-problem" issue will not be fixed. There is just too much risk in fixing something that doesn't affect your game nor the mechanics so I'm afraid the fix has to be done by Grovetama as it is his script

**Comment by ThisIsPatrick** [comment]
Are there any thoughts on revisiting this, now that Groovtama has removed the restrictive permissions on XPMSE?
https://forums.nexusmods.com/index.php?showtopic=3058149/#entry88845853

**Comment by BullOnMars** [comment]
This shit spams the log for more than 10k lines of errors every time you play, how about you STOP calling it a "Non Problem" when it fucking completely destroys anyone's ability to read the fucking Papyrus log, let alone trying to read other mods' debug message and finding script errors when creating mods. THIS bullshit needs to stop.

**Comment by mathi14811** [comment]
The perms are more permeative now, and Groovtama has updated the mod in 2023. However I still have those stacks:

> 	<unknown self>.fnis_aa.SetAnimGroupEX() - "FNIS_aa.psc" Line 8
> 	<unknown self>.xpmselib.SetAA() - "XPMSELib.psc" Line 238
> 	[Active effect 3 on  (0001A66C)].XPMSEWeaponStyleScaleEffect.SetAA() - "XPMSEWeaponStyleScaleEffect.psc" Line 1553
> 	[Active effect 3 on  (0001A66C)].XPMSEWeaponStyleScaleEffect.Restyle() - "XPMSEWeaponStyleScaleEffect.psc" Line 794
> 	[Active effect 3 on  (0001A66C)].XPMSEWeaponStyleScaleEffect.onBeginState() - "XPMSEWeaponStyleScaleEffect.psc" Line 255
> 	[Active effect 3 on  (0001A66C)].XPMSEWeaponStyleScaleEffect.GotoState() - "ActiveMagicEffect.psc" Line ?
> 	[Active effect 3 on  (0001A66C)].XPMSEWeaponStyleScaleEffect.OnEffectStart() - "XPMSEWeaponStyleScaleEffect.psc" Line 222
> [02/02/2024 - 06:53:49PM] ERROR: Static function SetAnimGroupLoad not found on object nemesis_aa. Aborting call and returning None

Has anyone found a solution yet? There's this mod : https://www.nexusmods.com/skyrimspecialedition/mods/44252, but it hasn't been updated since 2021.

**Comment by Thorbear** [comment]
For anyone arriving here after searching on google for this log message, like I did, this is now fixed by another mod: https://www.nexusmods.com/skyrimspecialedition/mods/60363

**Comment by uncleseano** [comment]
Very kind for the heads up, thanks!
