### ISSUE TITLE
Random race condition crashes

### ISSUE THREAD

**Issue by idaan300** [ShikyoKira/Project-New-Reign---Nemesis-Main#316]
I noticed when having lots of animations installed the generator becomes really crash happy. It doesn't throw an error. It just quits.
When i set cpu affinity to 1 thread not only does it consistently complete sucessfully (even at 19k anims) the generation is faster too (49 Seconds on 1 thread, 90+ on 12 threads).

**Comment by ShikyoKira** [comment]
I'm not sure how cpu affinity works behind the scene but even without multithreading the heavy stuffs, the program itself is already multithreaded with the UI and main backend thread as the most obvious 2 threads that will run concurrently regardless

I don't think the crash is the result of race condition as shared data will only be produced once by the main backend thread before initializing other threads, and then `const` all the way for all these worker threads, eliminating the need for lock. Perhaps i might have missed a thing or 2. I have tried hitting 22k animations while trying to fix another bug, I didn't have any data race related crash while doing the test, which prompted me to assume I have covered all

Another thing having my attention is the 90+s on 12 threads, while 49s on 1 thread, as there aren't many locks (a few) nor massive thread construction and destruction, since I'm using a threadpool here to reuse back idle threads

Overall, I still don't have any idea what's the cause. Is there any error message after the crash? What's the CPU utilization per core as well as CPU as a whole on 12 threads vs 1 thread?

**Comment by idaan300** [comment]
There is no error at all, the program just quits. I also want to add that whenever i change something about the animation mods i use (adding or subtracting) i'm forced to remove the folder nemesis creates in MO's Overwrite directory because regardless of anything else the program instant crashes when trying to generate (even if i update the engine first). If i remove the folder and let nemesis autoconfig itself and update its engine it works flawlessly. Regarding the threads question. When generating behaviors the cpu get usualy pinned at 90-95% on all threads (Cpu is an OC'ed Ryzen 2600). When running on 1 thread usage is ofcourse 8% (1 cpu thread at 100%).

**Comment by ShikyoKira** [comment]
1 more question, does increasing number of working threads, lead to higher chance of crash? What is the optimum number of threads for you?

**Comment by idaan300** [comment]
Allright, I went ahead and did some tests changing the thread affinity in task manager each time and this is what i found: 

12T:
 Update Engine: 22s
 Build Behavior: CTD
11T:
 Update Engine: 19s
 Build Behavior: CTD
10T:
 Update Engine: 19s
 Build Behavior: CTD
9T:
 Update Engine: 19s
 Build Behavior: CTD
8T:
 Update Engine: 20s
 Build Behavior: CTD
7T:
 Update Engine: 20s
 Build Behavior: CTD
6T:
 Update Engine: 20s
 Build Behavior: CTD
5T:
 Update Engine: 20s
 Build Behavior: CTD (PapyrusCompiler.exe did not exit propperly (Apparently a visual bug in MO2)
4T:
 Update Engine: 20s
 Build Behavior: CTD (PapyrusCompiler.exe did not exit propperly (Apparently a visual bug in MO2)
3T:
 Update Engine: 20s
 Build Behavior: CTD (PapyrusCompiler.exe did not exit propperly (Apparently a visual bug in MO2)
2T:
 Update Engine: 20s
 Build Behavior: CTD
1T:
 Update Engine: 20s
 Build Behavior: 54s With 18341 Anims

Every crash occured at random percentages but it was usually between 25 and 70%
I have the following patches loaded:
Archery Gameplay Overhaul
Combat Gameplay Overhaul
Go To Bed
Jump Behavior Overhaul
Ultimate Combat/TKdodge

Nemesis Also imported The following FNIS Anims:
Mod installed: ABBA
Mod installed: AnimationsByLeito
Mod installed: AnimationsByLeito_Aggressive
Mod installed: AnimationsByLeito_Furniture
Mod installed: Anubs Futa
Mod installed: Anubs Human
Mod installed: Bathing in Skyrim
Mod installed: Billyy_Human
Mod installed: Billyy_HumanFurniture
Mod installed: Billyy_HumanFuta
Mod installed: Billyy_HumanLesbian
Mod installed: CP_Elsie
Mod installed: dse-soulgem-oven
Mod installed: FHU
Mod installed: FunnyBizBeastly
Mod installed: FunnyBizFemDom
Mod installed: FunnyBizFun
Mod installed: FunnyBizGroup
Mod installed: FunnyBizLover
Mod installed: FunnyBizMolag
Mod installed: FunnyBizMtb
Mod installed: FunnyBizNecro
Mod installed: FunnyBizRape
Mod installed: FunnyBizUn
Mod installed: GTS
Mod installed: K4Anims
Mod installed: KomAnim
Mod installed: KomAnimT2Pack
Mod installed: milkypack
Mod installed: MME
Mod installed: NCK30
Mod installed: NibblesAnims_Human
Mod installed: NibblesAnims_Object
Mod installed: P1FlyingRing
Mod installed: SexLab
Mod installed: SexLabAP
Mod installed: SexLabAroused
Mod installed: SexLabCreature
Mod installed: testpack
Mod installed: TheMilkMaid
Mod installed: xpmse
Mod installed: ZaZAnimationPack
Mod installed: znarokspack

Now I want to also add that behavior generation started to get buggy when i installed the ZaZ Anim Pack 7.0
I was originaly planning to install 8.5 but that version kept crashing nemesis on 12 threads. This was before i found out that changing the affinity would help mittigate this.

Before i installed ZaZ i was getting around 70 to 80 seconds generation time on 12T with about 12k Animations.

The tests were run on the latest (0.84) version.

After Each test i removed the Nemesis_engine folder in MO as with it present i would crash regardless of configured cpu affinity
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878726/CriticalLog.txt)
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878727/PatchLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878728/UpdateLog.txt)
These are the logs of the sucessfull generation
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878735/UpdateLog.txt)
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878736/CriticalLog.txt)
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878737/PatchLog.txt)
And here are the logs of one of the many crashed attempts

So to awnser your question finaly i'd recomend you add a setting or a cmd line argument to be able to change the affinity of the program within itself instead of doing it in taskmanager for the less savy users that may experience the same problem.
