### ISSUE TITLE
 ERROR(3012) "ChickenProject.txt"

### ISSUE THREAD

**Issue by Valkrie13** [ShikyoKira/Project-New-Reign---Nemesis-Main#329]
**Checking engine version
Engine is up to date
Version Code: 5121-3770

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: dscgo
Mod Checked 3: dsmove

ERROR(3012): Duplicated unique code detected in InfoData section. Please contact the template creator
Project: ChickenProject.txt
Unique Code: 0

Failed to generate behavior**

As far as I have seen by searching on my PC's drives, there is no such thing as ChickenProject.txt, so I have no clue how to fix this problem. I've followed the installation tutorial video mentioned here and on the Nexus and have had no luck fixing this problem.

Multiple reinstalls later and nothing has fixed it.

I have tried using an earlier version of Nemesis, but when that version threw up this code too I returned to using the latest version of Nemesis.

LOOT and SSEEdit were used for all installs to make sure I'm running buttery smooth and no plugins are fighting each other, and all compatibility patches that any mods may need were installed.

If this was already discussed in a previous topic here, I have not seen it. Therefore, if there is one hopefully someone can link it so I can have a look and figure this out.

**Comment by Valkrie13** [comment]
OK so update on this, I'm seeing lots of duplicated clip name detected in "animationdatasinglefile.txt" under ChickenProject.txt with clip names showing various animations, which leads me to believe it's some animations doubling over or something in the animationdatasinglefile file. I think I'll try looking in the file and finding those duplicates.

**Comment by Valkrie13** [comment]
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4920397/PatchLog.txt)

This is the PatchLog that shows the errors for the ChickenProject thing.

**Comment by ShikyoKira** [comment]
Try it without anything but Nemesis. If you still have the same issue, then report it to me, if not, look for the culprit

**Comment by Valkrie13** [comment]
Uninstalled every mod while keeping SKSE64, reinstalled nemesis, updated the engine, and ran the engine.

Completed the run with no problems

Gonna see what mods might have caused the error

**Comment by Valkrie13** [comment]
Ok so it looks like the culprit may have been Joy of Perspective, because other than that mod, every other mod I had was installed again with no problem.
