### ISSUE TITLE
Goofy 2H attack animations when moving

### ISSUE THREAD

**Issue by MrTangoPIG** [ShikyoKira/Project-New-Reign---Nemesis-Main#332]
Hi,

I am using 2H katana attack animations SSE by mofu with this and Nemesis PCEA. 

When I attack with a 1h sword in 2h mode and whilst moving, my upper body starts moving in a freaky and unnatural manner. 
When I do the same but standing still, the animation matches that of the videos of the katana animation mod (I do not want to return to FNIS, as Nem PCEA allows for such seamless grip changing, I wont 2h otherwise).

**Comment by ShikyoKira** [comment]
can you take a video of it. i can't image it based on your description. Does this happen only to this animation mod? Do you have XMPSE installed?

**Comment by MrTangoPIG** [comment]
Only animation I have noticed (so far, my 1H is fine). I have uninstalled XPMSSE (However, this issue occurs with or without it).

**My vid:**
https://youtu.be/7xoaNgR0CmA
*(First ~40 secs of 2H (in motion = goofy), then final ~10 secs of 1H (fine).)

**Vid from the 2H katana mod page**
https://youtu.be/Ckt_34y5gYI

**Comment by ShikyoKira** [comment]
remove all mods and test again. I suspect CGO is causing it, if you don't have CGO, make sure you aren't checking any mods in the nemesis mod list when you test it again. If removing mods fixes it, then it isn't nemesis' issue. Bring this issue to the author

**Comment by MrTangoPIG** [comment]
Aha! CGO uninstalled, animation is normal. 
I will ask the author of CGO if there is something they can do.

Thanks for your help. :)

**Comment by ShikyoKira** [comment]
i don't think there is anything he can do about it as i know the underlying mechanics. Try don't bother him too much about it as he can't control what animation ppl use. Just bring it up casually, don't try to push it. If he can fix it, then good, if he can't, well, thats that then

Good luck
