### ISSUE TITLE
The Ultimate Dodge Mod stuck in place after race change

### ISSUE THREAD

**Issue by ODLI514** [ShikyoKira/Project-New-Reign---Nemesis-Main#334]
Hi! I was able to run TUDM alongside CGO, AGO, several other behavior mods thanks to Nemesis, I even managed to run FNIS, so thank you for all this.

I recently ran into a new issue in which TUDM bugged out after my character transforms back from beast form, and the dodge animation stucks in mid air untill I go back to MCM and manually reset the dodge option. It only happens after a werewolf transformation, everything else works just fine. After some research I realised that this seems to be a old bug within TUDM according to this reddit post; 

https://www.reddit.com/r/skyrimmods/comments/h12zg1/moonlight_tales_problems/

Unfortunately I couldnt find any existing fix for this bug, and I dont know any other way to contact you directly, so I decided to post it here. sorry for not being really related to Nemesis it self.

I saw one of your comments on https://bethesda.net/en/mods/skyrim/mod-detail/4011038 last year, saying that there will soon be a bug fix for the werewolf and vampire transform bug, is that still being work on? or has it already been posted some where that I couldnt find? If not, could you share some insight and point me toward the right direction on how to make a TUDM compatibility patch for either Growl or Moonlight Tales? Thank you once again!

edit: fix typo

**Comment by ShikyoKira** [comment]
![image](https://user-images.githubusercontent.com/31563634/87857065-62ca0a80-c956-11ea-9e83-c1a026d4e019.png)

thanks but already noted. And your issue breaks this criteria. It will be closed

**Comment by ODLI514** [comment]
> ![image](https://user-images.githubusercontent.com/31563634/87857065-62ca0a80-c956-11ea-9e83-c1a026d4e019.png)
> 
> thanks but already noted. And your issue breaks this criteria. It will be closed
> 
> Please be mindful of the criteria stated in the main page of this repo. I get pissed when people not following it

ah sorry, I am fairly new to all this and didnt realised the rules, so apologise for posting it in the wrong place. Just wanna ask if there is any discussion thread or forums for problems related to TUDM itself? I am still trying to figure out a way to use the mod smoothly while playing as a werebeast..
