### ISSUE TITLE
Trying to run nemesis for CGO

### ISSUE THREAD

**Issue by shathal** [ShikyoKira/Project-New-Reign---Nemesis-Main#335]
Running Nemesis from mod organizer 2, I tried all possible similiar issues here and none work.

Checking engine version
Engine is up to date
Version Code: 4838-8039

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: dscgo

Mod installed: XPMSE

ERROR(5001): Invalid format has been detected in "animationsetdatasinglefile.txt". Please contact the template creator or mod author
Project: DefaultFemaleData\DefaultFemale.txt
Header: DragonMountedMRhSolo_ShieldOrTorch.txt

Failed to generate behavior

**Comment by ShikyoKira** [comment]
have you read the criteria stated in the main page of this repo before posting this issue?

**Comment by ShikyoKira** [comment]
No update after 5 days. Closed
