### ISSUE TITLE
Feature Request: Run from command line.

### ISSUE THREAD

**Issue by Eggypapa** [ShikyoKira/Project-New-Reign---Nemesis-Main#336]
Hi ShikyoKira, thanks for working on this project!

I was hoping you would be willing to add the ability to call Nemesis from command line, as it would make it easier for automating it for when users are testing their setups and making changes.

Something like "Nemesis Unlimited Behavior Engine.exe --Update --Execute" to automatically update the engine and then execute would be an amazing QOL feature.

Thanks for giving up your time to make this tool, and I hope you consider my suggestion.

Cheers and thanks!
Eggy

**Comment by ShikyoKira** [comment]
already a thing don't worry. Its not stable in the latest version, but it is tested and working in the upcoming version so stay tuned

**Comment by Eggypapa** [comment]
Cheers!
Looking forward to the next update then!
