### ISSUE TITLE
System cannot find the path specified

### ISSUE THREAD

**Issue by breh97** [ShikyoKira/Project-New-Reign---Nemesis-Main#340]
![Nemesis excecutables](https://user-images.githubusercontent.com/69053492/89063590-0db2cf00-d32e-11ea-9e41-ae4cdb43b2e9.png)
![Exception caught](https://user-images.githubusercontent.com/69053492/89063606-13101980-d32e-11ea-8b6d-43e96953f4c2.png)

I am trying to install nemesis and CGO in skyrim se for the first time using MO2. When trying to run nemesis through MO2, a window entitled "exception caught" appears with the following message: "directory_iterator::directory_iterator: The system cannot find the path specified.: 'mod\' " (picture is attached). I have also included a picture of my executables for nemesis. I have tried reinstalling a couple times and running as administrator. Any help would be much appreciated!

**Comment by ShikyoKira** [comment]
your start in is empty

**Comment by breh97** [comment]
What should I include in it? I have tried my skyrim data folder and the folder that contains nemesis and the same thing happens

**Comment by breh97** [comment]
> your start in is empty

What should I include in it? I have tried my Skyrim data folder and the folder that contains nemesis and the same thing happens

**Comment by ShikyoKira** [comment]
You should go watch youtube how to add executable in MO2. Go do some research yourself on how to use MO2

**Comment by breh97** [comment]
I have been trying to figure this out all day. I have followed several tutorial videos on installing this and the same thing happens each time.

**Comment by ShikyoKira** [comment]
https://forums.nexusmods.com/index.php?/topic/1406725-mod-organizerhow-to-add-as-excutable/

![image](https://user-images.githubusercontent.com/31563634/89094537-774ae000-d3f7-11ea-8b91-799d7538dab3.png)

you shouldn't need to type in anything. They are all auto filled by MO2. If yours isn't look like this, then you probably following the general procedure for general users

**Comment by zcourge** [comment]
I woke up today, Nemesis working 100% fine yesterday, and noticed my 360 movement mod wasn't working, so I fired up Nemesis to patch again in case something was wrong, and I got the same error when trying to open it.

Nemesis is installed to my mods folder inside MO2, I have "Start in" set as the Nemesis_Engine folder, as seen in the picture below.
![2020-08-03 12_34_14-Skyrim Special Edition – Mod Organizer v2 3 1 (zCourge)](https://user-images.githubusercontent.com/24362254/89174173-b9a22780-d585-11ea-9831-1cdd18c960e2.png)

**Comment by ShikyoKira** [comment]
Thank you for finding out the truth and providing the solution to us all. I will close this issue now

**Comment by larinius** [comment]
I got the same error when MO2 moved and Skyrim directory changed.
```
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: copy_file: The system cannot find the path specified.
```
It wold be great if we could know what exactly patcher wants from us.

Does Nemethis want Skyrim path in registry? Because the game itself runs fine.

**Comment by SETA1609** [comment]
The real issue here is that nemesis should be in the same directory as skyrim.exe if not there breaks

**Comment by FOV-01** [comment]
Can be fixed by adding in “Start in” the path where the Nemesis executable is located but without including the drive letter.

Example:
Binary ```E:\Modding\MO2\mods\Nemesis\Nemesis_Engine\Nemesis Unlimited Behavior Engine.exe```
Start in ```\Modding\MO2\mods\Nemesis\Nemesis_Engine```
