### ISSUE TITLE
MO2 v 2.3.1 crashes on installing Nemesis 0.84

### ISSUE THREAD

**Issue by BlueGunk** [ShikyoKira/Project-New-Reign---Nemesis-Main#346]
Simply installing from the downloaded file, MO2 begins installation then crashes to desktop around two-thirds of the way through.
Event Manager shows:
Faulting application name: ModOrganizer.exe, version: 2.3.1.0, time stamp: 0x5f25952e
Faulting module name: ntdll.dll, version: 10.0.18362.815, time stamp: 0xb29ecf52
Exception code: 0xc0000374
Fault offset: 0x00000000000f9229
Faulting process ID: 0x527c
Faulting application start time: 0x01d66ccba5410070
Faulting application path: G:\GAMES\MOD MANAGERS\ModOrganizerSE\ModOrganizer.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report ID: ea5360ed-fc8a-4981-918e-33857726137c
Faulting package full name: 
Faulting package-relative application ID: 

Hope this helps. I will also advise MO2 team on Discord.  
Oh, found the same with v0.83 too...

**Comment by ShikyoKira** [comment]
well, the faulting application name is obvious there

I have received reports from my testers that reverting back to older version of MO2 fixes it. I'm not sure if it is the same issue but it highly suggests that it isn't Nemesis issue

**Comment by BlueGunk** [comment]
I am very much inclined to agree with you.  I got the Nemesis engine to work with MO2 by manually installing it. I think you can close this issue and thank you for responding!
Oh - and fantastic system thank you!
