### ISSUE TITLE
0.84 6001 bug

### ISSUE THREAD

**Issue by aimaozhai** [ShikyoKira/Project-New-Reign---Nemesis-Main#349]
0.83 is no problem
https://ftp.bmp.ovh/imgs/2020/08/7bed59f10473d079.jpg
 when using 0.84 can not update engine 
https://ftp.bmp.ovh/imgs/2020/08/c58e0ddae3861a19.jpg
update engine again Nemesis crash and say critical error
https://ftp.bmp.ovh/imgs/2020/08/293a116bcce41fda.jpg

**Comment by ShikyoKira** [comment]
Duplicate of #273
