### ISSUE TITLE
Animation False Positives

### ISSUE THREAD

**Issue by AreeSoothsayer** [ShikyoKira/Project-New-Reign---Nemesis-Main#355]
I get warnings like this, off and on.

[19-08-2020 21:35:25] WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture | File: E:\SteamLibrary\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\animations\Nemesis_PCEA\PCEA_animations\fp20_2hw_equip.hkx

Everything is right until I go into the Animation folder, then nothing.

**Comment by ShikyoKira** [comment]
this issue does not fit the terms and conditions in the main page of this repo. If after 5 days, it remains not meeting all the criteria, it will be deleted

**Comment by ShikyoKira** [comment]
elaborate. you are giving us the full picture here. what do you mean by nothing? what's the specs and so on?

**Comment by AreeSoothsayer** [comment]
Dang. I forgot to mention I am using Mod Organizer 2 so all the animations and such are not stored in my skyrim se folder. Yet I get that message for dozens of animations.

**Comment by AreeSoothsayer** [comment]
How the heck am I supposed to convert them to 64 bit?
