### ISSUE TITLE
Crash startup

### ISSUE THREAD

**Issue by max6186** [ShikyoKira/Project-New-Reign---Nemesis-Main#362]
after I install nemesis and combat gameplay overhaul my game crash in startup.

I attach list of mods I install before I add nemesis and CGO.

![some random list](https://user-images.githubusercontent.com/65102624/91086320-d222d080-e65f-11ea-9a45-ef1c47b74d38.png)

**Comment by ShikyoKira** [comment]
have you tried removing all other stuffs and test nemesis + CGO alone?

**Comment by max6186** [comment]
I try them alone and it work  just fine.

**Comment by max6186** [comment]
I find the source of the issue, it was BHUNP (it use HDT SMP, I turn it off.)
