### ISSUE TITLE
error �ڶ��ֽڵ�Ŀ������ҳ�У�û�д� Unicode �ַ�����ӳ�䵽���ַ���

### ISSUE THREAD

**Issue by safeblood** [ShikyoKira/Project-New-Reign---Nemesis-Main#364]
Initializing engine update

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: �ڶ��ֽڵ�Ŀ������ҳ�У�û�д� Unicode �ַ�����ӳ�䵽���ַ���

Failed to update engine

**Comment by zx-00001** [comment]
i hava same error with you   this is updatelog,txt `s content :ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately | Message: 在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。  and  ican switch language it leads to flash back

**Comment by JustAMerePleb** [comment]
I have the same error but in full english, maybe its caused by our system locale? only happen with 0.84 beta

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: No mapping for the Unicode character exists in the target multi-byte code page.

**Comment by ShikyoKira** [comment]
Duplicate of #273
