### ISSUE TITLE
Invalid string position.

### ISSUE THREAD

**Issue by Mihazutsu** [ShikyoKira/Project-New-Reign---Nemesis-Main#370]
<img width="264" alt="Capture" src="https://user-images.githubusercontent.com/70710462/92133566-61955580-edbd-11ea-9568-73a6d94bf917.PNG">
This error happened when I tried updating my nemesis version from the LE version to the SSE version on Skyrim SSE

**Comment by NeunLeben** [comment]
I had that same problem but it was my fault for not noticing the update. Are you sure you downloaded the latest one? It's the version 0.84 Beta. The author fixed that problem with this one.
![Releases · ShikyoKira_Project-New-Reign---Nemesis-Main and 13 more pages - Personal - Microsoft​ Edge 9_3_2020 2_59_40 PM (2)](https://user-images.githubusercontent.com/70699605/92156022-53aff680-edf6-11ea-8a04-ececb270232b.png)
![Releases · ShikyoKira_Project-New-Reign---Nemesis-Main and 13 more pages - Personal - Microsoft​ Edge 9_3_2020 3_01_44 PM (2)](https://user-images.githubusercontent.com/70699605/92156132-8954df80-edf6-11ea-830e-1f7d70da01cb.png)

**Comment by Mihazutsu** [comment]
Thank you Nuen Leben
