### ISSUE TITLE
Animations from a jump mod not working.

### ISSUE THREAD

**Issue by HomeGrownTeddybear** [ShikyoKira/Project-New-Reign---Nemesis-Main#393]
Hello, I've recently switched from FNIS to Nemesis because i've heard its better. I use flip animations from this mod. https://www.nexusmods.com/skyrim/mods/16069
I have them in female folder and checked gender specific animation.

**Comment by ShikiRyugi** [comment]
Ok..., so you installed the a.m. mod correctly, running Nemesis gave no error message, but the animation is not playing in the game?

Then what other animation mods do you have installed? 
Do you use PCEA / PCEA2 or the Dynamic Animation Replacer?

**Comment by HomeGrownTeddybear** [comment]
I use DAR but no animations for movement like jump, only idles so far, like EVG conditional idles. Started using Combat gameplay overhaul, Archery gameplay overhaul, tk dodge, 360 movement, if that counts.
Animations for combat I have in animations/ and animations/female folder
Also the problem with jump animations started when I switched from FNIS to Nemesis. They just didn't work anymore. I jump and character runs in air and then falls down.
I'll just have to remove all animations and install them one by one until I get to see what works and what doesn't.

**Comment by HomeGrownTeddybear** [comment]
Fixed this, closing.
