### ISSUE TITLE
KillCam NPC Falling And Rotating and flying into stratosphere

### ISSUE THREAD

**Issue by tectonicLeader** [ShikyoKira/Project-New-Reign---Nemesis-Main#396]
Here is a video example ignore the stuttering I did not have enough VRAM to actually make a good recording.  https://drive.google.com/file/d/1yuG6ZyBc5IzpyjiYRjaADOQTXcf6M2aA/view?usp=sharing
[modList.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5338385/modList.txt)
[loadorder.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5338392/loadorder.txt)
Ive been trying to diagnose this for a couple days with not luck  people I have been talking to have no idea either.  Its almost like the ragdoll isnt initiating with the killcam animation.

**Comment by ShikyoKira** [comment]
Reproduce this without any mod. If you can't, check your mods first before you come to me
