### ISSUE TITLE
Fuwa Poser, Knox Poser and Pinup Poser (removed from halo poser) unable to work together

### ISSUE THREAD

**Issue by tectonicLeader** [ShikyoKira/Project-New-Reign---Nemesis-Main#398]
It seems that even without additional animations these three crash the game before Bethesda logo.  It is stable at 16326 animations without Knox Poser but only behavior animations (specifically idles) and launched animations work (like posers).  Pinup and Knox work fine together and fuwa works fine by itself.

**Comment by ShikyoKira** [comment]
Post your patchlog.txt

**Comment by tectonicLeader** [comment]
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5360438/PatchLog.txt)

**Comment by tectonicLeader** [comment]
without spear combat under stable point still crashing.
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5360443/PatchLog.txt)

**Comment by tectonicLeader** [comment]
no true spear combat no pinup working as intended.
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5360473/PatchLog.txt)

**Comment by ShikyoKira** [comment]
based on this log, I am assuming you didn't read the description in the main page of this repo

Another I'm very sure however is you aren't using the latest version. Not using the latest version is wasting my time on a possible old issue. Try again
