### ISSUE TITLE
Error [5001] version v.0.84

### ISSUE THREAD

**Issue by GibsonCZ** [ShikyoKira/Project-New-Reign---Nemesis-Main#413]
ERROR(5001): Invalid format has been detected in "animationsetdatasinglefile.txt". Please contact the template creator or mod author
Project: DefaultFemaleData\DefaultFemale.txt
Header: DragonMountedMRhSolo_ShieldOrTorch.txt

Failed to generate behavior
Have this problem, was looking on #155 #338 #299 And still have this problem, but there is one bigger problem and that there are not files in Nemesis\Nemesis_Engine\temp_behaviors just only xml folder, no animationsetdatasinglefile.txt or PatchLog.txt.

If you could help me, I even tried #299 Locale Emulator @AmGarkin told. Even that didn't help.

[2020.10.29-21.33.zip](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5461123/2020.10.29-21.33.zip)

**Comment by AMGarkin** [comment]
I'm not good with MO2, but doesn't it create a new files in overwrite subfolder instead in mods?
It should be something like this: G:\MO2\SkyrimSE\overwrite\Nemesis_Engine\tem_behaviors\

**Comment by GibsonCZ** [comment]
> I'm not good with MO2, but doesn't it create a new files in overwrite subfolder instead in mods?
> It should be something like this: G:\MO2\SkyrimSE\overwrite\Nemesis_Engine\tem_behaviors\

I will look at it,but I did empty mod to keep overwrite files,idk if something messed up

**Comment by GibsonCZ** [comment]
@AMGarkin Can you please text me somewhere and in czech please ? via email gibson66cz@gmail.com the part about Locate Emulator, and I did the file thing in overwrite and it's running, just having other problem.

**Comment by GibsonCZ** [comment]
Somehow I fixed it, thanks @AMGarkin for help.
