### ISSUE TITLE
"no Qt platform plugin could be initialized" when starting through MO2

### ISSUE THREAD

**Issue by AtomCrafty** [ShikyoKira/Project-New-Reign---Nemesis-Main#418]
![image](https://user-images.githubusercontent.com/4553050/98158919-00345480-1edc-11eb-8300-d023ccaa90cb.png)

Nemesis starts fine from Windows Explorer, but won't load when launched through MO2.
Any ideas what could cause this or how to fix it?

Here's the MO2 executable setup, but it also happens when I start the executable from within the VFS explorer:

![image](https://user-images.githubusercontent.com/4553050/98163180-bdc24600-1ee2-11eb-8041-6a658a187048.png)

**Comment by AtomCrafty** [comment]
Turns out this was an issue with a symlinked game directory where Nemesis resolved the symlink rather than accessing the virtual file system created by MO2.

**Comment by escervo** [comment]
Hey, how did you fix it? I have the exact same issue and can't figure out what's the problem at all

**Comment by AtomCrafty** [comment]
My game directory was symlinked. Don't do that, the virtual file system doesn't support symlinks.

**Comment by escervo** [comment]
the problem is i didn't do any symlinking or anything, i did a fresh install

**Comment by AtomCrafty** [comment]
Then unfortunately I don't know what's causing your issue.
