### ISSUE TITLE
Nemesis not detecting CGO or 360 but working for other mods (Last resort)

### ISSUE THREAD

**Issue by Pipsqueak-Rat** [ShikyoKira/Project-New-Reign---Nemesis-Main#425]
![nemesis](https://user-images.githubusercontent.com/74609353/99405983-47134880-28e5-11eb-9f12-cd97d4f2336d.PNG)

This is me running nemesis with ultimate combat (working fine), CGO (not being recognised) and 360 movement behaviours (not being recognised). All three patch boxes are ticked but on the mod checks, nemesis is unable to see CGO or 360, but can be clearly seen patching Ultimate combat.

I've tried talking to the mod developers but they wont answer, the internet has no solution and even on mod discords no one could help. You are my last resort. All other functions of nemesis are fine and its a very well done animation manager. So thank you for that.

However nemesis seems to be doing something to both mods that I cant understand, as if both mods are installed without nemesis ever touching them, they work about half correct. Just a little janky and slower due to no nemesis patch. I use vortex and have installed both nemesis and the mods many times manually and through vortex. But no avail.

I'm sorry to bother as its most likely a simple answer but I just need help. I did download all patches and my current mods shouldn't effect CGO or 360 at all. But they still don't work. I have a mind that its the "animationsetdatasinglefile" but can figure out a solution. 

P.S Where exactly is the nemesis output folder. Is it:
SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Nemesis_Engine\mod\XXX

To know where I need to put the "setdatasinglefile"
With XXX being the mod I want to use.
Again thank you if you can help.

**Comment by Jorischi** [comment]
Hi, did you get this fixed? Im having the same problem

**Comment by Pipsqueak-Rat** [comment]
sorry never did get it fixed, all i really wanted was the leaning and the roll. so i settled with the ultimate dodge mod i think. or maybe tk dodge cant remember. i also found these options to be a great. hope this helps

**Comment by Jorischi** [comment]
Thanks for the reply. I managed to get it to work, but it makes no sense. I tried again and again without succes with Nemesis v 0.84, so I installed v0.83c, which worked. Then I uninstalled that one and reinstalled v0.84, and somehow it was fine
