### ISSUE TITLE
Compatibility issue with XP32 and changing forms IG

### ISSUE THREAD

**Issue by wJoenn** [ShikyoKira/Project-New-Reign---Nemesis-Main#437]
So I've installed Nemesis recently and since then XP32's weapon position are "disabled" after changing forms (Turning werewolf in my case)

To be a little bit more specific :
XP32 offer the option through MCM to change weapon's position (such as having sword on back, daggers in back hip, quiver position from "belt-fastened quiver" etc) and that works fine but if I ever turn into a werewolf then back to human, their position is reset BUT not in the MCM ! XP32's MCM menu is still here, I can still change weapons' position in the menu but it has no effect in game anymore. Reloading a save prior to turning werewolf solve the problem but if I ever turn into a werewolf again the problem is brought back.
I have this problem only with XP32's weapon position. I have around 5 animation mods, some through Nemesis PCEA, other on their own (Like Combat Gameplay Overhaul and Pretty Combat animation) and they work without any problem. Even XP32's animation (Draw weapon on back or dagger on back hip for exemple) work fine which means he still draws his sword from his back but the sword is on the hip.
It used to worked flawlessly with FNIS.

Is there a solution to this problem ? As it appeared at the moment I switch from FNIS to Nemesis I assume the latter is the source of it but just in case I asked to XP32's modder and he assured there was no such issue with the mod itself and confirmed that if I had no problem ever with FNIS and it appeared when changing to Nemesis it must come from this.

Thanks in advance for the help !

**Comment by AMGarkin** [comment]
At first try to correct typo in python script described in #422. With this fixed Nemesis will copy (after behavior files are generated) scripts which returns fake FNIS version number. This script is required by XPMSE to work correctly.

**Comment by wJoenn** [comment]
I just did, problem persists.

And I'll correct something I say, XP32's animations are not kept after changing forms either.
Which means that sword will go back to the hip and the animation of drawing from the back is changed to drawing from the hip (although everything is still set as "sword in the back" in XP32 MCM menu)

**Comment by wJoenn** [comment]
No ideas ?
I'm scared I'm gonna have to farm all my werewolf and vampire level in one go for the success then roll back to a prior save...

**Comment by wJoenn** [comment]
Closing because it's been years without fixes.
The issue might not even exist anymore, who knows
