### ISSUE TITLE
ERROR (4011): Alternate animation file has not been registered

### ISSUE THREAD

**Issue by coppertor** [ShikyoKira/Project-New-Reign---Nemesis-Main#459]
I thought this would be a common or at least easy issue to fix, but it seems that I'm the only person to ever report an error with a 4011 code.

Logs whenever I launch the engine:

Checking engine version
Engine is up to date
Version Code: 4838-1763

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: aarm
Mod Checked 3: dscgo
Mod Checked 4: tkuc

Mod installed: NAR
ERROR(4011): Alternate animation file has not been registered. Please contact the mod author
File: FNIS_XPMSE_List.txt
Line: 21
Animation File: xpe3_Dag_Unequip.hkx

Failed to generate behavior

Some potentially useful info: Judging from the description I'd assume it would have just prevented one mod from working, but this error stops all other animation mods in their tracks. I can't even find the the files that it references. Any help would be greatly appreciated!

**Comment by AMGarkin** [comment]
This error is related to mod "XP32 Maximum Skeleton Special Extended", you probably have corrupted or missing files in this mod.
Try to reinstall XPMSE mod and run Nemesis again.
