### ISSUE TITLE
Error 2006

### ISSUE THREAD

**Issue by Zarbon83** [ShikyoKira/Project-New-Reign---Nemesis-Main#499]
Excuse me there is something that I can do for this error? Many thanks in advance... Bye
![2021-03-24 20_55_36-New Issue · ShikyoKira_Project-New-Reign---Nemesis-Main](https://user-images.githubusercontent.com/44031514/112375629-ca093d00-8ce3-11eb-9183-26d0c669a6cc.jpg)

**Comment by Zarbon83** [comment]
Sorry there was already a solution...

**Comment by obaihumran** [comment]
howwwwwwwwwwww?
