### ISSUE TITLE
Error(6001) failed to update engine

### ISSUE THREAD

**Issue by bezarker943** [ShikyoKira/Project-New-Reign---Nemesis-Main#509]
Initializing engine update

ERROR(6001): An exception has occurred while updating. Report to Nemesis' author immediately
Message: invalid string position

Failed to update engine

**Comment by breadguy69** [comment]
getting the same thing here

**Comment by bezarker943** [comment]
I run Nemesis through Mod Organizer 2.  I had it configured so that the files were created in a mod rather than going to Overwrite.  Switching that off appears to have fixed the problem.

**Comment by breadguy69** [comment]
what? how did you do that

**Comment by bezarker943** [comment]
To run through MO2 first add as an executable by clicking on the gears icon at the top left.  Then click on the blue + icon.  “Add from file is probably the option you want or else fill in the details manually.  “Create files in mod rather than overwrite (*)” is one of the available options. If you enable (check) it you will need to have a mod into which to create it Uncheck it to disable.  To use it you will need to select it from your Run options in the main screen.
