### ISSUE TITLE
Gives weird animation error (NSFW) (image linked)

### ISSUE THREAD

**Issue by LegallyBlindGaming** [ShikyoKira/Project-New-Reign---Nemesis-Main#544]
https://ibb.co/VpS08dH

Not sure what is happening exactly. I've made sure to try and purge most of the creature animations since i know nemesis doesn't support them. But it still closes at 65% and like 3K animations. I know you can edit the nemsis ini to make it so the count is larger, which you kinda need for most adult animation packs. I don't see an update log or anything in my nemesis files so I sadly can't paste it here. Probably because it crashes. But i know this can work with adult animations and better than FNIS.

**Comment by DarthCrater** [comment]
This error is coming from Dynamic Animation Replacer, not Nemesis.
