### ISSUE TITLE
Nemesis don't find any animations if the path contains Data

### ISSUE THREAD

**Issue by epinter** [ShikyoKira/Project-New-Reign---Nemesis-Main#552]
Nemesis don't find any animation if the path where the game is installed contains the string "data".

For example a ntfs volume mounted at D:\data, when the game installed in D:\data\SteamLibrary\steamapps\common\Skyrim Special Edition, Nemesis find 0 animations.

The same volume mapped to E: (changed nemesis.ini to E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\), finds all my animations, no other changes made.

I reinstalled nemesis from scratch a few times.

**Comment by epinter** [comment]
Is this mod abandoned ?

**Comment by alexdelifer** [comment]
You have no idea how much time I wasted over this issue...
I thought it was Linux specific or something, but nope, changed my mountpoint to /games instead of /data/games and bam everything works...

Cheers
