### ISSUE TITLE
Can't get nemesis to work ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately

### ISSUE THREAD

**Issue by bluesquares01** [ShikyoKira/Project-New-Reign---Nemesis-Main#586]
Nemesis has been working fine since I started using it and then all of a sudden I get this error one day and now I cant get to it  to work at all, someone please help.

I keep getting this message every time I run it it now. I don't get it it's always ran without issue in the past.

Checking engine version
Engine is up to date
Version Code: 2143-4678

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: tkuc
Mod Checked 3: itmuse

Mod installed: XPMSE
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: copy_file: The system cannot find the path specified.

Failed to generate behavior

or I get this message.

Checking engine version
Engine is up to date
Version Code: 2143-4678

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: tkuc
Mod Checked 3: itmuse

Mod installed: XPMSE

ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: _1stperson\1hm_locomotion.txt
Message: copy_file: The system cannot find the path specified.: "cached_behaviors\SSE\_1stperson\1hm_locomotion.hkx", "d:\steam\steamapps\common\skyrim special edition\data\meshes\actors\character\_1stperson\behaviors\1hm_locomotion.hkx"

Failed to generate behavior

If anyone could help me it would be much appriciated, thank you.

**Comment by coocookachoo** [comment]
Think I saw on an earlier post, I was having the same issue. Turns out it was the antivirus not allowing scripts to run. Turned off realtime protection and it worked first try.

**Comment by bluesquares01** [comment]
Just tried it and that's exactly what the problem was, thank you so much!  I've been trying to get this working for days with no luck.
