### ISSUE TITLE
Crashing due to this error

### ISSUE THREAD

**Issue by Spek-comm** [ShikyoKira/Project-New-Reign---Nemesis-Main#601]
Having this issue all of a sudden whenever launching after updating, closes right after displaying the message.
![image](https://user-images.githubusercontent.com/90787912/133472482-7c9c6eec-ccfd-401f-bf51-c1b798c3f686.png)

**Comment by duffbeeeer** [comment]
Yep same here

**Comment by MagicalPrincessUnicorn** [comment]
Have you guys tried the solution I mentioned in #591?

**Comment by Spek-comm** [comment]
> Have you guys tried the solution I mentioned in #591?

This does indeed work, thank you.
