### ISSUE TITLE
ERROR (6002) need help.

### ISSUE THREAD

**Issue by max6186** [ShikyoKira/Project-New-Reign---Nemesis-Main#628]
I was try to install animations but I got this in log window while the process:

Checking engine version
Engine is up to date
Version Code: 8272-1723

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: dscgo
Mod Checked 3: tdmv

Mod installed: XPMSE

ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: Alternate Animation
Message: copy_file: The system cannot find the path specified.: "alternate animation\alternate animation 2.script", "C:\Users\lions\AppData\Local\Nemesis\FNIS_aa.psc"

Failed to generate behavior

what is the problem?

**Comment by SUOMALILI** [comment]
bro,i got the same problem and i don't know why

**Comment by plrns000** [comment]
You can try:
1- Disable your anti-virus protection, further more make your skyrim and your mod manager folder excluded. If using windows defender, disable your real-time protection.
2- Make sure that you have installed .NET 3.5 and enabled it through windows features(type it on the search bar)
3- Last weird solution for some people is changing windows’ language, region and time zone to USA
