### ISSUE TITLE
Error 5020,3012

### ISSUE THREAD

**Issue by XEntity171** [ShikyoKira/Project-New-Reign---Nemesis-Main#669]
Skyrim se

I have a problem, it started slow with the slide not moving anywhere (crouch sliding mod) than all of a sudden ultimate dodge mod stopped moving at all after that skysa stopped moving as well. I tried removing the 'animationsetdatasinglefile.txt file and replace it with another animationsetdatasinglefile.txt someone kindly sent and nemesis launched until 99 but then got another error 

"ERROR(3012): Duplicated unique code detected in InfoData section. Please contact the template creator | Project: ChickenProject.txt | Unique Code: 0"

[animationdatasinglefile.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/7692231/animationdatasinglefile.txt)

The Original Error Prior Replacing 'animationsetdatasinglefile.txt' is "ERROR(5020): Invalid format has been detected in "animationsetdatasinglefile.txt". Please contact the template creator | File: temp_behaviors\animationsetdatasinglefile.txt | Line: 94035"

[animationsetdatasinglefile.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/7692230/animationsetdatasinglefile.txt)

**Comment by FanaticalLikeADemon6** [comment]
I had this issue and fixed it finally

https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/issues/677
