### ISSUE TITLE
Error 6002

### ISSUE THREAD

**Issue by 1cornmilk** [ShikyoKira/Project-New-Reign---Nemesis-Main#670]
So I changed my Skyrim SE game folder to Downloads and I have been playing for a while with no problems. I have updated and launched Nemesis Engine with this directory and had no problems. However, today LOOT told me that Nemesis may be curropted and I need to reinstall and update the engine so I did just that. I did all of that, no problems. However, when I tried to launch the engine, this happened:

Checking engine version
Engine is up to date
Version Code: 9064-1723

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: dscgo
Mod Checked 3: para
Mod Checked 4: tdmv

Mod installed: ImmersiveAnimatedLooting
Mod installed: XPMSE
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: copy_file: The system cannot find the path specified.

Failed to generate behavior

I have tried to add exceptions for both the game folder, mod folder and the exe file on Windows Defender.
I have uninstalled and reinstalled Nemesis countless of times but had zero success.
I will attach the PatchLog.txt for more info

Thanks in advanc
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/7697503/PatchLog.txt)
e

**Comment by Rafuc** [comment]
FOUND THE SOLUTION,CHANGE THE COMPATIBILITY MODE TO WINDOWS 7 AND IT WORKS

**Comment by 1cornmilk** [comment]
Actually I found a "fix" a few days ago:
Adding the .exe as an exception on the antivirus doesnt work, however if you disable RTP Nemesis works just fine.
Thanks for your input tho
