### ISSUE TITLE
Error Code 2003 Initializing engine update  ERROR(2003): Invalid file name. File name must only be #<modcode>$<id> or #<id>. Please contact the mod author File: mod\amco\animationdatasinglefile\DefaultFemale.txt  Failed to update engine

### ISSUE THREAD

**Issue by Alpha719a** [ShikyoKira/Project-New-Reign---Nemesis-Main#744]
When using MO2 and nemesis and the popular mod ADXP MCO I get this error message 

Initializing engine update

ERROR(2003): Invalid file name. File name must only be #<modcode>$<id> or #<id>. Please contact the mod author
File: mod\amco\animationdatasinglefile\DefaultFemale.txt

Failed to update engine

and I did fix this issue before but I don't remember what I did I had to reinstall all mods and wipe my MO2 not because of the update but I made the mistake on my part to delete a mod mid playthrough and then I couldn't open any non owned containers or lockpick any containers it would CTD or freeze my game so I decided to reinstall most of my mods and got the game to work except I get a t pose problem because I can't get the Nemesis to work out the above issue much help would be appreciated please and thank you

**Comment by Alpha719a** [comment]
I had to delete overwrite files to fix the issue

**Comment by Wizrdman94** [comment]
alpha, how do i find the overwrite files when using vortex? same error for same filename.
