### ISSUE TITLE
ERROR 1166

### ISSUE THREAD

**Issue by ImShEthan** [ShikyoKira/Project-New-Reign---Nemesis-Main#753]
Hello,
tried to install TK dodge & ultimate combat got this error : 
I got precision & true direction movement too
```
Checking engine version
Engine is up to date
Version Code: 5770-5385

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: colis
Mod Checked 3: tdmlen
Mod Checked 4: tdmv
Mod Checked 5: tkuc

ERROR(1166): BUG FOUND!! Report to Nemesis' author immediately
Variable Name: <1>

Failed to generate behavior
```
[PatchLog.txt](https://github.com/user-attachments/files/17787733/PatchLog.txt)

**Comment by Void-alexis** [comment]
Hi, how did you solve this error?

**Comment by ImShEthan** [comment]
Hi,
It's been a while, but if I remember correctly, the issue was caused because I had checked a mod in Nemesis that I didn't actually have installed.
Sorry, I can't recall which one it was exactly...
Hope this helps!
