### ISSUE TITLE
Nemesis should ignore "__folder_managed_by_vortex"

### ISSUE THREAD

**Issue by wSedlacek** [ShikyoKira/Project-New-Reign---Nemesis-Main#87]
When using Nemesis with Vortex an error occurs when Updating Engine.
Error causes Nemesis to freeze up and cause significant CPU usage.

Error:
`
ERROR(2003): Invalid file name. File name must only be #<modcode>$<id> or #<id>. Please contact the mod author
File: mod\agpo\weapequip\__folder_managed_by_vortex
`

This error is coming from functionupdate.cpp line 498 (or 505)

Purposed Fixes:
Create an else if to ignore "__folder_managed_by_vortex" on line 473 of functionupdate.cpp
Add additional releases and catches when error occurs in FunctionUpdate to avoid CPU continuing to run even after error.

**Comment by ShikyoKira** [comment]
noted. I don't use Vortex so i have no idea this will happen. Anyway, thanks for the finding out the issue and coming up with a fix for me
