### ISSUE TITLE
Client cannot be resized to view hidden information

### ISSUE THREAD

**Issue by BenjaminAtbi** [ShikyoKira/Project-New-Reign---Nemesis-Main#88]
In the client window, Mod Name and Mod Author columns are fixed width and cannot be resized to view overflow text. 

Additionally, text cannot be highlighted to follow nexus links.

**Comment by ShikyoKira** [comment]
if you hover over the row, there will be a drop down showing the full text. Tho i know its quite a hassle.

Apparently fixing the size is to prevent stretching issue. Let me see if there is anything else i can do to make it possible.

**Comment by ShikyoKira** [comment]
Fixed in v0.82b
