### ISSUE TITLE
Error6002

### ISSUE THREAD

**Issue by andrelo1** [ShikyoKira/Project-New-Reign---Nemesis-Main#95]
Error(6002) if path "Data\meshes\actors\character\animations\" doesn't exist.

**Comment by ShikyoKira** [comment]
full message please. The message is there for me to diagnose the problem not for fun

**Comment by ShikyoKira** [comment]
Best if you can provide the patchlog.txt

**Comment by ShikyoKira** [comment]
Nvm, i don't know which commit if fixed it. But yeah... it has already been fixed in unreleased version. Thanks again
