### ISSUE TITLE
[Compatibility Enhancement] Character Behaviors Enhanced needs cross/bows anims work underwater and staves on horseback

### ISSUE THREAD

**Issue by cygarniczka** [ShikyoKira/Project-New-Reign---Nemesis-Main#96]
Load order for Nemesis:
Ultimate Combat SSE
The Ultimate Dodge Mod
Character Behaviors Enhanced

Issue:
Bows & crossbows don't work underwater
Staves don't work on horseback
Weapons need to be pulled out before entering swimming (dunno if this by design of the mod CBE)

Everything else works jumping attacks, swimming attacks, magic and dodges etc. Even dodge from TUDM can be hooked up to Ultimate Combat by checking the proper box in Ultimate Combat MCM.

I previously tried TK Dodge mod instead of TUDM. TUDM plays far better with Character Behavior Enhanced than TK Dodge.
With TUDM

**Comment by ShikyoKira** [comment]
All these features you are having are from CBE. Test this in a clean setup with only CBE

**Comment by cygarniczka** [comment]
I was kind of wrong all the issues. Report can be closed down.
From the description on the mod page:
> Weapons need to be pulled out before entering swimming (dunno if this by design of the mod CBE)
>use the sneak key to draw while underwater

>Bows & crossbows don't work underwater
>  Bows, crossbows, torches and ritual spells are the exceptions. You also cannot attack with your left hand when underwater.

>Staves don't work on horseback
I did as you recommended by running clean game with USSEP and Character Behavior Enhanced + Racemenu and Alternative Start. Can't use staves on horseback.
