### ISSUE TITLE
[Compatibility] Nemesis chokes on True Spear Combat - related to _1stperson folder

### ISSUE THREAD

**Issue by cygarniczka** [ShikyoKira/Project-New-Reign---Nemesis-Main#97]
https://www.nexusmods.com/skyrimspecialedition/mods/10483

ERROR(1003): Failed to output hkx file
File: temp_behaviors\xml\1hm_locomotion.xml
&&&
File: temp_behaviors\xml\0_master.xml

This mod adds behaviors to the 1st person. 

I tried on clean install with only Alternative Start, Racemenu, SkyUI, and Unofficial Skyrim Special Edition Patch with no other behavior mod. 

Removing **_1stperson** folder from True Spear Combat - SSE - Patchs - NMM Installer\meshes\actors\character\_1stperson folder
will make the True Spear Combat generate behaviors correctly in Nemesis. 

It probably chokes on 1st person animations/behaviors/ or skeleton.

TSC generated correctly (no _1stperson folder):
![True Spear Combat First Person Removed](https://user-images.githubusercontent.com/17316115/58057676-c038b080-7b33-11e9-8e7e-7d06c22f89bd.jpg)

TSC behavior generation error (with _1stperson folder):
![Nemesis chokes on True Spears Combat](https://user-images.githubusercontent.com/17316115/58057738-01c95b80-7b34-11e9-8409-82b5d8d95e17.jpg)

**Comment by ShikyoKira** [comment]
thanks for reporting will look into it

**Comment by ShikyoKira** [comment]
doesn't seem to be able to reproduce this in latest version. Tell me if the latest version fixes this problem. I will leave this open for another 2 days unless the issue still persist in your setup despite using the latest version
