### ISSUE TITLE
Provide warning for incorrectly converted/bad animation and skeleton

### ISSUE THREAD

**Issue by cygarniczka** [ShikyoKira/Project-New-Reign---Nemesis-Main#99]
I was battling T-Pose and it turned out it was caused by incorrectly converted animation mod from Oldrim to SSE. Simply removing this mod and regenerating behavior solved the T Pose bug.

**Comment by ShikyoKira** [comment]
good suggestion but i have to weight the performance impact of it. I'll give it a look

**Comment by cygarniczka** [comment]
Why not make it optional so it will serve as good troubleshooting tools for those that have problem.

**Comment by ShikyoKira** [comment]
yea that should do. Let me see if i can find a way to toggle it

**Comment by ShikyoKira** [comment]
Added in v0.83
